In [9]:
import tensorflow as tf
import numpy as np
import os

In [10]:
print('Tensorflow version : {0}'.format(tf.__version__))

Tensorflow version : 1.1.0


In [11]:
embedding_size = 5
vocabulary_size = 10

#Create a sample embedding matrix

embedding = np.random.rand(vocabulary_size,embedding_size)
print(embedding)

[[ 0.79051364  0.0603627   0.94822885  0.65949765  0.93386573]
 [ 0.12211158  0.70227698  0.59684181  0.61090058  0.43581856]
 [ 0.05148149  0.66870287  0.16233297  0.78750426  0.32894886]
 [ 0.50373446  0.73188621  0.85936606  0.50906838  0.67036793]
 [ 0.17757405  0.91211475  0.25774803  0.53043361  0.43624868]
 [ 0.46793564  0.24568717  0.6956468   0.95532604  0.61926156]
 [ 0.19687118  0.64523553  0.85081125  0.72603572  0.14200174]
 [ 0.01807328  0.93888406  0.68773283  0.40539571  0.90316513]
 [ 0.36627616  0.7877704   0.67498527  0.58194454  0.77682707]
 [ 0.61284408  0.01025248  0.49613339  0.50291687  0.67326658]]


In [12]:
i = 4
one_hot = np.zeros(10)
one_hot[i] = 1.0
print(one_hot)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [13]:
embedding_vector = np.dot(one_hot,embedding)
print(embedding_vector)

[ 0.17757405  0.91211475  0.25774803  0.53043361  0.43624868]


In [14]:
print(embedding[i])

[ 0.17757405  0.91211475  0.25774803  0.53043361  0.43624868]


In [18]:
g = tf.Graph()
with g.as_default():
    x = tf.placeholder(shape=[None],dtype = tf.int32, name='x')
    
    weights_initializer = tf.constant_initializer(embedding)
    embedding_weights = tf.get_variable(
                            name = 'embedding_weights',
                            shape = (vocabulary_size,embedding_size),
                            initializer = weights_initializer,
                            trainable = False)
    embedding_lookup = tf.nn.embedding_lookup(embedding_weights,x)

In [20]:
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(embedding_lookup,feed_dict={x : [4]}))

[[ 0.17757405  0.91211474  0.25774804  0.5304336   0.43624869]]
