In [2]:
import pandas as pd
import numpy as np

In [3]:
def ciphertextFor(text, key):
    cpt = []
    for i in range(len(text)):
        cpt.append(chr((ord(text[i])+ord(key[i])) % 26+65))
    return ''.join(cpt)

In [5]:
ciphertextFor('ajshwhsuhe','amchaksheo')

'MHGAIDWNXE'

In [9]:
''.join([chr((ord(text[i])+ord(key[i])) % 26+65) for i in range(len(text))])

'MHGAIDWNXE'

In [24]:
length = 5
a = {'this':1, 'is':2, 'an':3, 'example':4}

out = pd.DataFrame({0:[a] * 5})
print(out)

                                             0
0  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
1  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
2  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
3  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
4  {'this': 1, 'is': 2, 'an': 3, 'example': 4}

                                             0
0  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
1  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
2  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
3  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
4  {'this': 1, 'is': 2, 'an': 3, 'example': 4}


0
0  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
1  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
2  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
3  {'this': 1, 'is': 2, 'an': 3, 'example': 4}
4  {'this': 1, 'is': 2, 'an': 3, 'example': 4}

In [106]:
text, key = 'ajshwhsuhe','amchaksheo'

In [107]:
%timeit ''.join(chr((ord(text[i])+ord(key[i])) % 26+65) for i in range(len(text)))

3.47 µs ± 60 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [108]:
%timeit ''.join(chr((ord(x)+ord(y)) % 26+65) for x,y in zip(text, key))

3.17 µs ± 27.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [109]:
def c(a,b):
    return chr((ord(a)+ord(b)) % 26+65)

cv = np.vectorize(c)

%timeit ''.join(cv(list(text), list(key)))

28.5 µs ± 118 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [114]:
df

Location       ID
0                 DS  12973.0
1                 DS  12955.0
2                 DS  12947.0
3           St. paul  12949.0
4  Bakersfield 12097      NaN
5             Vernon  12905.0
6             vernon  12096.0
7             vernon  12902.0

In [122]:
df = pd.read_clipboard('\s\s+')

In [121]:
Location   ID
DS         12973
DS         12955
DS         12947
St. paul   12949
Bakersfield  12097
Vernon     12905
vernon     12096
vernon     12902

Location       ID
0                 DS  12973.0
1                 DS  12955.0
2                 DS  12947.0
3           St. paul  12949.0
4  Bakersfield 12097      NaN
5             Vernon  12905.0
6             vernon  12096.0
7             vernon  12902.0

In [123]:
df

Location     ID
0           DS  12973
1           DS  12955
2           DS  12947
3     St. paul  12949
4  Bakersfield  12097
5       Vernon  12905
6       vernon  12096
7       vernon  12902

In [129]:
df['Location'] = df['Location'].apply(str.lower)

df.groupby('Location')['ID'].apply(list).to_dict()

{'bakersfield': [12097],
 'ds': [12973, 12955, 12947],
 'st. paul': [12949],
 'vernon': [12905, 12096, 12902]}

{'bakersfield': [12097],
 'ds': [12973, 12955, 12947],
 'st. paul': [12949],
 'vernon': [12905, 12096, 12902]}

In [139]:
[sum(inputArray[i:i+k]) for i in range(len(inputArray)-1)]

[5, 8, 6, 7]

In [175]:
inputArray = [2, 3, 5, 1, 6]
k = 3

In [170]:
inputArray = np.random.randint(0,100,1000)
k = 30

In [174]:
def arrayMaxConsecutiveSum(inputArray, k):
    #begin = 0 #<--- #No need since you are setting it to i in loop
    #end = begin + k #<--- Not to be defined here but inside loop
    sum_list = []
    
    for i in range(0, len(inputArray)-1): #<----
        begin = i
        end = begin + k #<--- 
        sum_list.append(sum(inputArray[begin:end])) #<----
    return sum_list

arrayMaxConsecutiveSum(inputArray, k)

[5, 8, 6, 7]

In [184]:
#OPs approach
%timeit arrayMaxConsecutiveSum(inputArray, k)

1.49 µs ± 55.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [185]:
%timeit [sum(inputArray[i:i+k]) for i in range(len(inputArray)-1)]

1.39 µs ± 65.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [183]:
%timeit [sum(i) for i in zip(*[inputArray[i:] for i in range(k)])]

1.46 µs ± 65.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [201]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(2,2,4)
np.max(arr.reshape(2,-1),-1)

array([ 8, 16])

In [205]:
arr[:,:,-1]

array([[ 4,  8],
       [12, 16]])

In [206]:
A = np.array([[2,3],[5,4]])
B = 4

In [209]:
res = []
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if(A[i][j] == 2):
            res += B == 0

TypeError: 'bool' object is not iterable

In [275]:
import itertools

In [276]:
kk = 'ABCDEFGHIJKLMNOPQURSUVWXYZ'
mydict = {i:np.random.randint(1,10000) for i in itertools.combinations(kk,2)}
len(mydict)

def h():
    cols = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')

    df = pd.DataFrame(0, columns=cols, index=cols)

    for i in mydict.items():
        df.loc[i[0]] = i[1] 

    df = df + df.T

In [279]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(2,2,4)
print(arr)

np.max(arr.reshape(2,-1),-1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


array([ 8, 16])

In [ ]:
df = pd.read_clipboard('\s\s+')

for peptide in peptides:
    model=LogisticRegression()
    model.fit(X_train[peptide], y_train)
    score = model.score(X_test[peptide], y_test)
    y_pred=model.predict(X_test[peptide])
    acc_score = accuracy_score(y_test, y_pred)
    LR_scores.append(peptide,acc_score)
    
    #Classification Report
    print (classification_report(y_test,y_pred))
    
    #Confusion Matrix
    cnf_matrix = confusion_matrix(y_test,y_pred)
    print(cnf_matrix)
    
    #ROC_AUC Curves
    y_predict_proba = model.predict_proba(X_test[peptide])
    probabilities = np.array(y_predict_proba)[:, 1]
    fpr, tpr, thresholds = roc_curve(y_test, probabilities, pos_label=1)
    roc_auc = auc(fpr, tpr)
    logit_roc_auc = roc_auc_score(y_test, model.predict(X_test[peptide]))

In [277]:
mydict={('A', 'E'): 23972,
 ('A', 'D'): 10730,
 ('A', 'B'): 14748,
 ('A', 'C'): 3424,
 ('E', 'D'): 3294,
 ('E', 'B'): 16016,
 ('E', 'C'): 3373,
 ('D', 'B'): 69734,
 ('D', 'C'): 4662,
 ('B', 'C'): 159161}

cols = np.unique(list(mydict.keys())).ravel()

df = pd.DataFrame(None, columns=cols, index=cols)

for i in mydict.items():
    df.loc[i[0]] = i[1] 
    
print(df)

     A      B       C      D      E
A  NaN  14748    3424  10730  23972
B  NaN    NaN  159161    NaN    NaN
C  NaN    NaN     NaN    NaN    NaN
D  NaN  69734    4662    NaN    NaN
E  NaN  16016    3373   3294    NaN


In [230]:
import seaborn as sns
from sklearn.model_selection import train_test_split

df = sns.load_dataset('titanic')

cols = ['pclass','sex','age']
df = df[cols]

train, test = train_test_split(df,test_size=0.1)
[i.shape for i in [train,test]]

[(801, 3), (90, 3)]

In [247]:
means = train.groupby(['pclass','sex'])['age'].mean()

In [248]:
means

pclass  sex   
1       female    34.848101
        male      41.649111
2       female    29.007576
        male      31.129556
3       female    21.335227
        male      26.675739
Name: age, dtype: float64

In [249]:
df.mean()

pclass     2.308642
age       29.699118
dtype: float64

In [272]:
cnt = []
sm = []

lista = [3, 3, 5, [[1, 8, [9, 3]], 3, [2, [9, [5, 6], [9]]]]]

#function to iterate over a reversed list
f = lambda x: [g(i) for i in reversed(x)]

#function to call f if list else updated counters and return element
def g(x):
    if type(x)==list:
        return f(x)
    else: 
        cnt.append(1)
        sm.append(x)        
        return x
    
#call f and return sum of counters
def rec(l):
    o = f(l)
    return o,(sum(cnt),sum(sm), sorted(sm))


out, tup = rec(lista)

print(out)
print(tup)
#[[[[[9], [6, 5], 9], 2], 3, [[3, 9], 8, 1]], 5, 3, 3]
#(13, 66, [1, 2, 3, 3, 3, 3, 5, 5, 6, 8, 9, 9, 9])

[[[[[9], [6, 5], 9], 2], 3, [[3, 9], 8, 1]], 5, 3, 3]
(13, 66, [1, 2, 3, 3, 3, 3, 5, 5, 6, 8, 9, 9, 9])


In [278]:
f = lambda x: [g(i) for i in reversed(x)]
g = lambda x: f(x) if type(x)==list else x

f(lista)

[[[[[9], [6, 5], 9], 2], 3, [[3, 9], 8, 1]], 5, 3, 3]

In [273]:
list_x = ['a:1_b:45_c:abc','a:2_b:24_c:def','a:4_b:78_c:xxx']
dict_x = {'a':[1,2,4],'b':[45,24,78],'c':['abc','def','xxx']}

def convert(tup):
    di = {}
    for a, b in tup:
        if b.isdecimal():
            b = int(b)
        di.setdefault(a, []).append(b) 
    return di 

k = [tuple(j.split(':')) for i in list_x for j in i.split('_')]
convert(k)

{'a': [1, 2, 4], 'b': [45, 24, 78], 'c': ['abc', 'def', 'xxx']}

In [283]:
ColumnSelector(cols='tweet',drop_axis=True)

ColumnSelector(cols='tweet', drop_axis=True)

In [284]:
TfidfVectorizer.fit_transform(ColumnSelector(cols='tweet',drop_axis=True).fit_transform(df_Xtrain))

TypeError: fit_transform() missing 1 required positional argument: 'raw_documents'

In [285]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from mlxtend.feature_selection import ColumnSelector
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB



df_Xtrain = pd.DataFrame({'tweet': ['This is a tweet']*10,
                          'label': 0})
y_train = df_Xtrain['label'].to_numpy().ravel()

pipe = Pipeline([
    ('col_selector', ColumnSelector(cols=('tweet'),drop_axis=True)),
    #('count_vectorizer',CountVectorizer()),
    ('tfidf', TfidfVectorizer()),
    ('bernoulli', BernoulliNB()),
])


pipe.fit(df_Xtrain,y_train)

Pipeline(steps=[('col_selector', ColumnSelector(cols='tweet', drop_axis=True)),
                ('tfidf', TfidfVectorizer()), ('bernoulli', BernoulliNB())])

In [344]:
df = pd.DataFrame({'A': {0: 1, 1: 2, 2: 2, 3: 3, 4: 4, 5: 5, 6: 5, 7: 5, 8: 6, 9: 7, 10: 7}, 'B': {0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k'}})

In [345]:
df

A  B
0   1  a
1   2  b
2   2  c
3   3  d
4   4  e
5   5  f
6   5  g
7   5  h
8   6  i
9   7  j
10  7  k

In [304]:
# total_len = len(df.index)
# for i in range(total_len):
#         if df['A'].loc[i] == df['A'].loc[i+1]: 
#             df['A'].drop(df['A'].index[i+1])
#         else:
#             df['A']
            
# #KeyError: 11

In [439]:
dup = [True]
for i in range(1, total_len):
    if df.iloc[i]['A'] == df.iloc[i-1]['A']:
        dup.append(False)
    else:
        dup.append(True)
        
print(df[dup])

   A  B
0  1  a
1  2  b
3  3  d
4  4  e
5  5  f
8  6  i
9  7  j


In [449]:
df[df.ne(df.shift())['A']]

A  B
0  1  a
1  2  b
3  3  d
4  4  e
5  5  f
8  6  i
9  7  j

In [459]:
df[~df.eq(df.shift()).A]

A  B
0  1  a
1  2  b
3  3  d
4  4  e
5  5  f
8  6  i
9  7  j

In [461]:
df = pd.read_clipboard()

In [ ]:
sale_id brand   Qty
1       Toyota  1
1       Toyota  2
2       Honda   1
2       Toyota  1
3       Lexus   3

In [462]:
df

sale_id   brand  Qty
0        1  Toyota    1
1        1  Toyota    2
2        2   Honda    1
3        2  Toyota    1
4        3   Lexus    3

In [469]:
df1 = df.pivot_table(index='sale_id',columns='brand',values='Qty',aggfunc='sum',fill_value=0)
print(df1)

brand    Honda  Lexus  Toyota
sale_id                      
1            0      0       3
2            1      0       1
3            0      3       0

brand    Honda  Lexus  Toyota
sale_id                      
1            0      0       3
2            1      0       1
3            0      3       0


In [471]:
np.arange(0,10).astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])