In [ ]:
import numpy as np

In [ ]:
import multiprocessing as mp

fo = ["folder1","folder2","folder3","folder4"]
fi = ["csvfile1","csvfile2","csvfile3","csvfile4"]

def combine(a,b):
    print("Completed: ",a,'->',b)

pool = mp.Pool(processes=4)
results = [pool.apply_async(combine, args=(x)) for x in zip(fo,fi)]

##################################

results = pool.starmap_async(combine, zip(fo,fi))
# it needs `.get()` because it is `async`
print(results.get())

# non-async version

results = pool.starmap(combine, zip(fo,fi))
# it doesn't needs `.get()` because it is not `async`
print(results)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_clipboard('\s\s+')

In [ ]:
df1 = df.iloc[:,:4].copy()

In [ ]:
df

In [ ]:
o = 'D'

#Home and Away
home = np.array([1 if i==o else 0 for i in df['Home_Team']])
away = np.array([1 if i==o else 0 for i in df['Away_Team']])

#Wins and losses
wins = np.array([1 if i==o else 0 for i in df['Winner']])
loss = np.array([1 if (i==1 or j==1) and k==0 else 0 for i,j,k in zip(home, away, wins)])

#Streak
streak = np.array(df['Streak'])
truth = np.multiply(streak,home)

In [ ]:
print('home:',home)
#print('away:',away)
print('wins:',wins)
print('loss:',loss)                
print('true:',truth)    

In [ ]:
df = pd.DataFrame({'id':[1,1,1,2,2,2,2],'stage':[11,12,15,11,14,12,12],'value':[5,4,6,12,2,8,3]})

In [ ]:
df.loc[df.sort_values(['id','stage'])['stage'].eq(12)]

In [ ]:
df.sort_values(['id','stage'])

In [ ]:
df

In [ ]:
idx = df['stage'].eq(12).groupby(df['id']).transform('idxmax')
output = df[df.index <= idx].groupby('id')['value'].sum().reset_index()

In [ ]:
list(df['stage'].eq(12).groupby(df['id']))#.apply('idxmax')

In [ ]:
output

In [ ]:
Location        DeptCode
Delhi           12B
Gurgoun         12D 
Hydrabad        13A 
Punjab          20A
Jhansi          31B

In [ ]:
Department        DeptCode
Electronics       [12A, 12B, 12C, 12D, 12E]
Electronics       [13A,13B,13Z]
Grocery           [20A]
Grocery           [31A,31B,31C]

In [4]:
df2 = pd.read_clipboard('\s\s+')

In [5]:
df1 = pd.read_clipboard('\s\s+')

In [2]:
import pandas as pd

In [12]:
df2['DeptCode'].astype(list)

TypeError: dtype '<class 'list'>' not understood

In [7]:
df2.columns

Index(['Department', 'DeptCode'], dtype='object')

In [9]:
df2.explode('DeptCode')

Department                   DeptCode
0  Electronics  [12A, 12B, 12C, 12D, 12E]
1  Electronics              [13A,13B,13Z]
2      Grocery                      [20A]
3      Grocery              [31A,31B,31C]

In [13]:
def mu_brokaw(mus, mws, xs):
    n = len(mus)
    mu_mix = 0.0

    for i in range(n):
        d = 0.0

        for j in range(n):

            if j != i:
                mij = ((4 * mws[i] * mws[j]) / ((mws[i] + mws[j])**2))**0.25

                num = (mws[i] / mws[j]) - (mws[i] / mws[j])**0.45
                den = 2 * (1 + mws[i] / mws[j]) + ((1 + (mws[i] / mws[j])**0.45) / (1 + mij)) * mij
                aij = mij * ((mws[j] / mws[i])**0.5) * (1 + num / den)

                sij = 1.0
                d = d + sij * aij * xs[j] / np.sqrt(mus[j])

        mu_mix = mu_mix + (xs[i] * np.sqrt(mus[i])) / (xs[i] / np.sqrt(mus[i]) + d)

    return mu_mix

In [22]:
def mu_brokaw2(mus, mws, xs):
    mij = ((4 * np.outer(mws, mws)) / ((np.add.outer(mws, mws))**2))**0.25

    num = np.divide.outer(mws, mws) - np.divide.outer(mws, mws)**0.45
    den = 2 * (1 + np.divide.outer(mws, mws)) + (1 + np.divide.outer(mws, mws)**0.45) / (1 + mij) * mij
    aij = mij * (np.divide.outer(mws, mws)**0.5) * (1 + num / den)
    

    sij = 1.0
    d = np.sum(sij * aij * xs / np.sqrt(mus))

    mu_mix = np.sum((xs * np.sqrt(mus)) / (xs / np.sqrt(mus) + d))
    return mu_mix

In [94]:
mws = [mu_h2, mu_n2]
mws

[179.75, 363.87]

In [145]:
for i in range(len(mws)):
    for j in range(len(mws)):
        if j!=1:
            mij = ((4 * mws[i] * mws[j]) / ((mws[i] + mws[j])**2))**0.25
            num = (mws[i] / mws[j]) - (mws[i] / mws[j])**0.45
            den = 2 * (1 + mws[i] / mws[j]) + ((1 + (mws[i] / mws[j])**0.45) / (1 + mij)) * mij
            aij = mij * ((mws[j] / mws[i])**0.5) * (1 + num / den)
            print('mij:',mij)
            print('num:',num)
            print('den:',den)
            print('aij:',aij)
            print('')

mij: 1.0
num: 0.0
den: 5.0
aij: 1.0

mij: 0.9699985212194215
num: 0.6508237371110792
den: 7.217293844392621
aij: 0.7432396159359344



In [148]:
mij = ((4 * np.outer(mws, mws)) / ((np.add.outer(mws, mws))**2))**0.25
mij

array([[1.        , 0.96999852],
       [0.96999852, 1.        ]])

In [149]:
num = np.divide.outer(mws, mws) - np.divide.outer(mws, mws)**0.45
num

array([[ 0.        , -0.23407834],
       [ 0.65082374,  0.        ]])

In [150]:
den = 2 * (1 + np.divide.outer(mws, mws)) + (1 + np.divide.outer(mws, mws)**0.45) / (1 + mij) * mij
den

array([[5.        , 3.83886836],
       [7.21729384, 5.        ]])

In [151]:
mij, num, den = np.delete(mij, 1, 1), np.delete(num, 1, 1), np.delete(den, 1, 1)

In [157]:
mij

array([[1.        ],
       [0.96999852]])

In [156]:
np.divide.outer(mws, mws)**0.5

array([[1.        , 0.70284786],
       [1.42278303, 1.        ]])

In [155]:
aij = mij * (np.divide.outer(mws, mws)**0.5) * (1 + num / den)
aij

array([[1.        , 0.70284786],
       [1.50454853, 1.05746871]])

In [41]:
# dynamic gas viscosity in µP
mu_h2 = 179.75
mu_n2 = 363.87

# molecular weight in g/mol
mw_h2 = 2.016
mw_n2 = 28.014

# mole fraction
x_h2 = 0.85
x_n2 = 0.15

mu_mix = mu_brokaw([mu_h2, mu_n2], [mw_h2, mw_n2], [x_h2, x_n2])
print(f'mu_mix = {mu_mix:.4f}')

mu_mix2 = mu_brokaw2([mu_h2, mu_n2], [mw_h2, mw_n2], [x_h2, x_n2])
print(f'mu_mix2 = {mu_mix2:.4f}')

mu_mix = 257.9015
mu_mix2 = 41.1099


In [14]:
import numpy as np

In [37]:
mus = np.random.randint(1,3,(5,5))
mws = np.random.randint(1,3,(5,5))
xs = np.random.randint(1,3,(5,5))

In [38]:
mu_brokaw(mus, mws, xs)

array([1.42678486, 1.32703334, 1.80771414, 1.47523829, 1.87029408])

In [23]:
mu_brokaw2(mus, mws, xs)

ValueError: operands could not be broadcast together with shapes (225,225) (15,15,15,15) 

In [160]:
df = pd.read_clipboard(',')

In [161]:
df.drop()

user  item  timestamp  state_label  comma_separated_list_of_features
0 0   0.0     0        0.1          0.3                              10.7
2 1   6.0     0        0.2          0.4                               0.6
5 0  41.0     0        0.1         15.0                               0.6
3 2  49.0     1      100.7          0.8                               0.9