In [ ]:
import pandas as pd
df = {'text': ['Expression of H-2 antigenic specificities on', 'To study the distribution of myelin-associated'], 
     'id': [1, 2]}

df = pd.DataFrame(df)

In [ ]:
def chunks(s, c=2):
    return [s[i:i + c] for i in range(0, len(s), c)]


df['text'] = df['text'].apply(lambda x: chunks(x.split()))
df = df.explode('text').reset_index(drop=True)
df['text'] = df['text'].apply(' '.join, 1)

print(df)

In [ ]:
df

In [ ]:
df.groupby('id').cumcount()//2

In [ ]:
l = ['a1-23','b1-24','c1-25','c1-x-25'] 

In [ ]:
[i for i in l if 'c1' not in i.split('-') or 'x' in i.split('-')]

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense

In [ ]:
model=tf.keras.models.Sequential([
    Conv2D(32, 3, activation='relu', input_shape=(500, 500, 1)),
    MaxPooling2D(3,3),
    Conv2D(64, 3, activation='relu'),
    MaxPooling2D(3,3),
    Conv2D(128, 3, padding='same', activation='relu'),
    MaxPooling2D(3,3),
    Conv2D(256, 3, padding='same', activation='relu'),
    MaxPooling2D(3,3),
    Flatten(),
    Dropout(0.5), 
    Dense(32, activation='relu'),
    Dense(2, activation='softmax') # dense layer has a shape of 2 as we have only 2 classes 
])

In [ ]:
model.summary()

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'a':[1,1,2,2,3],  'b':[4,5,6,7,8]})
print(df)

In [ ]:
print(df.groupby(['a']).apply(lambda x:x**2))

In [ ]:
print(df.groupby(['a'])[['b']].apply(lambda x:x**2))

In [ ]:
import numpy as np
X = np.random.uniform(low=-1, high=10, size=(20,10))

In [ ]:
X = np.random.uniform(low=-1, high=10, size=(20,10))

In [ ]:
X

In [ ]:
out = np.sum((X<0).astype(int), axis=1)

In [ ]:
out[out==0]=1

In [ ]:
out

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'A':["1600 - 1700 mm","1600 - 1700 mm","1600 - 1700 mm"]})

In [ ]:
df

In [ ]:
df = pd.DataFrame({'A':["1600 - 1700 mm","1500 - 1800 mm","2000 - 1500 mm"]})

def mean_str(s):
    nums = [int(i) for i in s.split() if i.isnumeric()]
    return sum(nums)/len(nums)

df['avg'] = df['A'].apply(lambda x: mean_str(x))

print(df)

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    [
        ['2001-01-01 00:00:00',  12.283668,  144.341919],
        ['2001-01-01 00:10:00',  12.510790,  146.267975],
        ['2001-01-01 00:20:00',  12.072737,  144.149414],
        ['2001-01-01 00:30:00',  11.349895,  np.nan    ],
        ['2001-01-01 00:40:00',  12.352266,  145.304810],
        ['2001-01-01 00:50:00',  12.158932,  149.255615],
        ['2001-01-01 01:00:00',  11.581405,  148.387939],
        ['2001-01-01 01:10:00',  11.265101,  147.616882],
        ['2001-01-01 01:20:00',  10.692064,  148.387939],
        ['2001-01-01 01:30:00',  10.568085,  142.801880],
        ['2001-01-01 01:40:00',  10.609320,  137.800354],
        ['2001-01-01 01:50:00',  10.241758,  137.704224],
        ['2001-01-01 02:00:00',   9.988804,  142.513153],
        ['2001-01-01 02:10:00',  10.999095,  143.186829],
        ['2001-01-01 02:20:00',  10.258151,  142.609375],
        ['2001-01-01 02:30:00',  10.243141,  148.484314],
        ['2001-01-01 02:40:00',   9.856313,  150.220032],
        ['2001-01-01 02:50:00',   9.535853,  151.570801],
        ['2001-01-01 03:00:00',   9.850568,  149.448486],
        ['2001-01-01 03:10:00',   9.961300,  149.544922],
        ['2001-01-01 03:20:00',  10.692064,  990       ],
        ['2001-01-01 03:30:00',  10.568085,  142.801880],
        ['2001-01-01 03:40:00',  10.609320,  137.800354],
        ['2001-01-01 03:50:00',  10.241758,  137.704224],
    ], columns=['date', 'WindSpeed', 'WindDir']
    )

df = df.set_index('date')
df.index = pd.DatetimeIndex(df.index)
resampled = df.groupby(pd.Grouper(freq='H'))   # Data from 14.30 to 15.29 are rounded to 15.00

aggfuns = {'WindSpeed': np.mean, 'WindDir':meandir}
print(resampled.agg(aggfuns))

In [ ]:
from scipy.interpolate import CubicSpline

In [ ]:
df = pd.DataFrame({'combined': [[0.97, 0.92, 0.65, 0.24, 0.15, 0.19],
                                [0.96, 0.86, 0.69, 0.38, 0.56, 0.78],
                                [0.64, 0.69, 0.93, 0.07, 0.73, 0.05],
                                [0.29, 0.56, 0.35, 0.76, 0.19, 0.07]]})

In [ ]:
new_df = pd.DataFrame({'0': {0: 0.97, 1: 0.96, 2: 0.64, 3: 0.29},
                       '1': {0: 0.92, 1: 0.86, 2: 0.69, 3: 0.56},
                       '2': {0: 0.65, 1: 0.69, 2: 0.93, 3: 0.35},
                       '3': {0: 0.24, 1: 0.38, 2: 0.07, 3: 0.76},
                       '4': {0: 0.15, 1: 0.56, 2: 0.73, 3: 0.19},
                       '5': {0: 0.19, 1: 0.78, 2: 0.05, 3: 0.07}})

In [ ]:
def frequency_changer(y):
    x_val_30 = [] 
    for i in range(0, len(y), 4):
        x_val_30.append(i)


    x_val = [] 
    for i in range(len(y)):  
        x_val.append(i)
    y_val = y
    cs = CubicSpline(x_val, y_val)
    x2 = cs(x_val_30)
    print(x2)
    return x2

def prt(y):
    return y

def test(y):
    return [len(y),sum(y)]

In [ ]:
new_df

In [ ]:
df['combined'].apply(test)

In [ ]:
new_df.apply(test)

In [ ]:
new_df

In [ ]:
import numpy as np

m = np.array([[5,3,  6,7,  3,8],
              [5,4,  5,1,  4,5],
              [5,4,  2,4,  4,6],
              [2,2,  2,3,  8,5],
              [2,7,  8,7,  1,2],
              [2,7,  8,7,  3,2],
              [2,7,  8,7,  4,2]]) 

n = np.array([[1,3,  6,7,  1,12],
              [2,4,  2,9,  4,9],
              [1,5,  5,12, 9,1],
              [5,4,  5,6,  9,5],
              [5,4,  1,4,  1,5],
              [5,4,  1,7,  9,5],
              [5,4,  1,5,  4,11]])


mm = m.reshape(m.shape[0],-1,2)
nn = n.reshape(m.shape[0],-1,2)

matches_m = np.any(mm[:,:,None,:,None] == mm[:,None,:,None,:], axis=(-1,-2))
matches_n = np.any(nn[:,:,None,:,None] == nn[:,None,:,None,:], axis=(-1,-2))

mask = np.repeat(~np.eye(mm.shape[1], dtype=bool)[None,:], mm.shape[0], axis=0)

is_valid1 = np.all(np.any(matches_m&mask, axis=-1), axis=-1)
is_valid2 = np.all(matches_n[matches_m].reshape(mm.shape[0],-1), axis=-1)

m[is_valid1 & is_valid2]

In [ ]:
%%timeit

M = np.array([[1,3,  2,1,  4,2,  3,3],
              [3,5,  6,9,  5,1,  3,4],
              [1,3,  2,4,  3,4,  7,2],
              [4,5,  1,2,  2,1,  2,3],
              [6,4,  4,1,  6,1,  4,7],
              [6,7,  7,6,  9,7,  6,2],
              [5,3,  1,5,  3,3,  3,3]])

MM = M.reshape(M.shape[0],-1,2)

matches_M = np.any(MM[:,:,None,:,None] == MM[:,None,:,None,:], axis=(-1,-2))
mask = ~np.eye(MM.shape[1], dtype=bool)[None,:]

is_valid = np.all(np.any(matches_M&mask, axis=-1), axis=-1)
M[is_valid]

In [ ]:
%%timeit

M = np.array([[1,3,  2,1,  4,2,  3,3],
              [3,5,  6,9,  5,1,  3,4],
              [1,3,  2,4,  3,4,  7,2],
              [4,5,  1,2,  2,1,  2,3],
              [6,4,  4,1,  6,1,  4,7],
              [6,7,  7,6,  9,7,  6,2],
              [5,3,  1,5,  3,3,  3,3]])

a = M.reshape(M.shape[0],-1,2)

mask = ~np.eye(a.shape[1], dtype=bool)[...,None]

is_valid = (((a[...,None,:]==a[:,None,...])&mask).any(axis=(-1,-2))
            |((a[...,None,:]==a[:,None,:,::-1])&mask).any(axis=(-1,-2))
           ).all(-1)

M[is_valid]

In [ ]:
X = np.random.uniform(-5,5,(10,2))

In [ ]:
np.sqrt(np.sum(np.square(np.subtract(X[:,None,:], X[None,:,:])), axis=-1))

In [ ]:
def euclidean(point1, point2):
    return ((point1[0]-point2[0])**2 + (point1[1]-point2[1])**2)**(1/2)

euclidean_v = np.vectorize(euclidean, signature="(n),(n)->()")

euclidean_v(X[:,None,:], X[None,:,:])

#Again returns a (10,10)

In [ ]:
import numpy as np
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
np.ix_(True,[slice(0,3),4])

In [ ]:
df = pd.read_clipboard()
df

In [ ]:
%%timeit

df.groupby(['course_id']).apply(lambda x: sum(x['mark']*x['weight'])/sum(x['weight']))

In [ ]:
%%timeit

df.assign(wa = df['mark'] * df['weight'] / 100).groupby('course_id')['wa'].sum()

In [ ]:
lst = [   [['A'],['A'],['B'],['B'],['A'],['A']],
          [['B'],['B'],['A'],['A'],['B'],['B']],
          [['A'],['A'],['B'],['B'],['A'],['A']],
          [['B'],['B'],['A'],['A'],['B'],['B']],
          [['A'],['A'],['B'],['B'],['A'],['A']],
          [['B'],['B'],['A'],['A'],['B'],['B']],
  ]

In [ ]:
lst

In [ ]:
iterator = [[[k for k in j] for j in i] for i in lst]
iterator

In [ ]:
np.random.seed(123)
c1 = np.random.randint(0,100,size = 1000000)
c2 = np.random.randint(0,20,size = 1000000)
c3 = np.random.choice([1,-1],1000000 )
m = np.vstack((c1, c2, c3)).T
m = m[m[:,0].argsort()]

In [ ]:
df=np.array([[1,1,0.1,11],
             [1,2,0.2,12], 
             [1,3,0.3,13], 
             [1,4,0.4,14], 
             [2,5,0.5,15], 
             [2,6,0.6,16], 
             [2,7,0.7,17],
             [3,8,0.8,18],
             [3,9,0.9,19],
             [3,10,0.7,20]])

lookback=1
batch_size=2
offset = 1

def window_split_2d(g, window):
    shp = (g.shape[0] - window + 1, window, g.shape[-1])
    strd = (g.strides[0], g.strides[0], g.strides[1])
    return np.lib.stride_tricks.as_strided(g, shape=shp, strides=strd)

def get_batches_vectorized(df, target, id_col_index, lookback, offset, batch_size):

    #Break array into unequal length groups based on id_column
    groups = np.split(df, np.where(np.diff(df[:,id_col_index]))[0]+1)
    
    #Get rolling windows over axis=0 using stride tricks
    chunks = [window_split_2d(i,lookback+offset+1) for i in groups]
    
    #Stack all the windows into a block
    block = np.vstack(chunks)
    
    #Calculate number of batches possible
    n_batches = block.shape[0]//batch_size
    
    #Keep only the number of blocks that can successfully be stacked into equal sized batches
    keep = block.shape[0]-(block.shape[0]%batch_size)
    block = block[:keep]
    
    #Split block by num batches and get X
    X = np.split(block[:,:lookback,1:], n_batches)

    #Split block by num batches and get y
    y = np.split(block[:,-1,target], n_batches)
    return X, y

In [ ]:
def take(xs, runs, skip_size):
    'https://stackoverflow.com/questions/65163947/iterate-over-a-list-based-on-list-based-on-a-list-of-steps'
    ixs = iter(xs)
    for run_size in runs:
        for _ in range(run_size ):
            yield next(ixs)
        for _ in range(skip_size):
            next(ixs)
            
def get_batch(df, target, lookback, offset, batch_size):
    _ , c = np.unique(df[:,0], return_counts=True)
    rows = (lookback+offset+1)
    w = c-rows+1
    itr = take(range(len(df)), w, lookback+offset)
    while 1:
        X, Y = [],[]
        for _ in range(batch_size):
            k = next(itr, 'out of batches!')
            x = df[k:lookback+k, 1:]
            y = df[rows+k-1:rows+k, target]
            X.append(x)
            Y.append(y)
        try: yield np.stack(X), np.stack(Y)
        except: break
            
            
lookback = 1
offset = 1
batch_size = 1
target = slice(2,4) #set the target as a slice instead of a separate df view

windows = get_batch(df, target, lookback, offset, batch_size)

no_batches = int(np.sum(np.unique(df[:,0], return_counts=True)[1] - lookback - offset)/batch_size)

for i in range(no_batches):
    input,output=next(windows)
    print("{}th batch: \ninput is:\n{}\n and \ntarget is:\n{}\n".format(i+1, input, output))

In [ ]:
def windowGeneratorByID(data, target, id_col_index, lookback, offset, batch_size=16):
    min_index=0
    max_index = data.shape[0]-offset
    i = min_index + lookback
    while 1:
        if i + batch_size >= max_index:
            i = min_index + lookback
        rows = np.arange(i, min(i + batch_size, max_index))
        i += len(rows)
        samples = np.zeros((len(rows), lookback, data.shape[-1]))
        targets = np.zeros((len(rows), target.shape[-1]))
        print(samples, targets)
        
        for j, row in enumerate(rows):
            indices = range(rows[j] - lookback, rows[j])
            print(indices)
            if data[rows[j] + offset][id_col_index] in set(data[indices][:, id_col_index]):
                print(data[rows[j] + offset][id_col_index])
                print(set(data[indices][:, id_col_index]))
                if len(set(data[indices][:, id_col_index])) == 1:
                    samples[j] = data[indices]
                    targets[j] = target[rows[j] + offset]
    
        yield  np.delete(samples,id_col_index,axis=2) , targets

In [ ]:
lookback=1
batch_size=1
offset = 1
windows = windowGeneratorByID(data=df, target=df[:,2:4],id_col_index=0 , offset=offset, lookback=lookback,batch_size=batch_size)

#The number of total batches are equal to the number of (training examples - lookback-offset)/batch_size 
no_batches=int((df.shape[0]-lookback-offset)/batch_size)

# #print the batches
#for i in range(no_batches):
  #get the next batch from the windowGenerator
    #input,output=next(windows)
    #rint("{}th batch: \ninput is:\n{}\n and \ntarget is:\n{}\n".format(i+1, input, output))

In [ ]:
import math
import numpy

a = '2 5 6 7'
b = '4 9 10 12'

a = np.array(list(map(int,a.split())))
b = np.array(list(map(int,b.split())))

def gcd(p,q):
    while q != 0:
        p, q = q, p%q
    return p

def is_coprime(x, y):
    return gcd(x, y) == 1

is_coprime_v = np.vectorize(is_coprime)
compare = is_coprime_v(a[:, None], b[None, :])

noncoprime_pairs = [(a[i],b[j]) for i,j in np.argwhere(~compare)]
coprime_pairs = [(a[i],b[j]) for i,j in np.argwhere(compare)]

print('non-coprime',noncoprime_pairs)
print('coprime',coprime_pairs)

non-coprime [(2, 4), (2, 10), (2, 12), (5, 10), (6, 4), (6, 9), (6, 10), (6, 12)]
coprime [(2, 9), (5, 4), (5, 9), (5, 12), (7, 4), (7, 9), (7, 10), (7, 12)]

In [ ]:
import math
import numpy

a = '2 5 6 7'
b = '4 9 10 12'

a = np.array(list(map(int,a.split())))
b = np.array(list(map(int,b.split())))

def f(x,y):
    return math.gcd(x, y) == 1

fv = np.vectorize(f)
compare = fv(a[:, None], b[None, :])

noncoprime_pairs = [(a[i],b[j]) for i,j in np.argwhere(~compare)]
coprime_pairs = [(a[i],b[j]) for i,j in np.argwhere(compare)]

print('non-coprime',noncoprime_pairs)
print('coprime',coprime_pairs)

In [ ]:
%%timeit

import math
import numpy

a = '2 5 6 7'
b = '4 9 10 12'

a = np.array(list(map(int,a.split())))
b = np.array(list(map(int,b.split())))

def f(x,y):
    return math.gcd(x, y) == 1

fv = np.vectorize(f)
compare = fv(a[:, None], b[None, :])

noncoprime_pairs = [(a[i],b[j]) for i,j in np.argwhere(~compare)]

In [ ]:
%%timeit

import math
from itertools import product

a = '2 5 6 7'
b = '4 9 10 12'

a = np.array(list(map(int,a.split())))
b = np.array(list(map(int,b.split())))

#print(sum([math.gcd(x, y) != 1 for x, y in product(a, b)]))  # 8
[(x, y) for x, y in product(a, b) if math.gcd(x, y) != 1]

In [ ]:
(2000, 1300), (1300, 800), (800, 600)

In [ ]:
a = np.random.randint(0,2,(5,4))
b = np.random.randint(0,2,(4,3))
c = np.random.randint(0,2,(3,2))

final_output = (a @ b @ c)
final_output.shape

#(2000, 600)

In [ ]:
prod = a[:,None,:] * b.T[None,:,:]

In [ ]:
prod.shape

In [ ]:
c.shape

In [ ]:
a[:,:,None].shape

In [ ]:
b[None,:,:].shape

In [ ]:
Lets talk about the problem statement with a toy example. 

Lets consider 3 binary matrices - 

```
a = np.random.randint(0,2,(5,4)) #(5,4)
b = np.random.randint(0,2,(4,3)) #(4,3)
c = np.random.randint(0,2,(3,2)) #(3,2)
```

Now, lets build 'connections' the matrix `a` to matrix `b`. Lets take the second row of `a` and second column of `b`.
```
a_row2 = [1,1,0,0]
b_col2 = [0,1,1,1]
```
According to the connections you mention, you basically take a elementwise product. 
```
connection = [0,1,0,0]
```

Therefore, for each row in `a` (of which there are 5) and for each column in `b` (of which there are 3), you will get a 4 length `connection`. This means that your resulting matrix is going to be 5X3X4 (or 5X4X3 if you want to chain this operation with c)

This can be done with broadcasting as - 

```
connections_ab = a[:,:,None] * b[None,:,:]  
#(5,4,1) * (1,4,3) -> (5,4,3)
```

Now, since we have another matrix `c` (3,2), we can again create `connections` between the previous output (5,4,3) and (3,2) to get (5,4,3,2).
This can again be done with broadcasting.

```
connections_abc = connections_ab[:,:,:,None] * c[None,None,:,:] 
#(5,4,3,1) * (1,1,3,2) -> (5,4,3,2)
```
Performing all of this in a single step with broadcasting over `a`, `b` and `c` - 

```
connections_abc = a[:,:,None,None] * b[None,:,:,None] * c[None, None, :, :]
#(5,4,1,1) * (1,4,3,1) * (1,1,3,2) -> (5,4,3,2)
```

Now you can imagine the outer most dimensions as rows of `a` and columns of `b`, while the axis 1 and axis 2 represent connections between `a,b` and `b,c`.
Transposing the `connections_abc` you can get the (4,3) matrix that shows how each row in `a` is connected to each column in `c`. 

```
connections_abc2 = connections_abc.transpose(0,3,1,2)
#(5,2,4,3)
```

So, if you want to know the `connections` for row 4 of `a` and row 1 of `b`. Then - 

```
connections_abc2[4,1,:,:]
```
```
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])
```

Hope that makes sense. 


In [ ]:
connections_abc2[4,1,:,:]

In [ ]:
connections_abc = a[:,:,None,None] * b[None,:,:,None] * c[None, None, :, :]

In [ ]:
connections_abc2 = connections_abc.transpose(0,3,1,2)
connections_abc2.shape

In [ ]:
connections_ab = a[:,:,None] * b[None,:,:]  #(5,4,1) * (1,4,3) -> (5,4,3)
connections_abc = connections_ab[:,:,:,None] * c[None,None,:,:] #(5,4,3,1) * (1,1,3,2) -> (5,4,3,2)

In [ ]:
A = np.array([ 1.23853755+1.15170502j, -1.2041678 +1.38375402j,
              1.28973689+1.2755069j ,  -1.29422454-1.28925842j,
              -1.33236945-1.22467046j,  1.25472049+1.27488595j])

coords = np.vstack([A.real, A.imag]).T

labels = ['r+ij', '-r+ij', '-r-ij', 'r-ij']
signs = np.array([[True,True], [False,True], [False,False], [True,False]]) #r+ij, -r+ij, -r-ij, r-ij

boolean = np.all(~(signs[:,None]^np.where(coords>0,True,False)[None,:]), axis=-1) #XNOR with broadcasting

#boolean - 
# [[ True False  True False False  True]
#  [False  True False False False False]
#  [False False False  True  True False]
#  [False False False False False False]]

output = {labels[i]:A[j] for i,j in enumerate(boolean)}
output

In [ ]:
arr=np.array([[1., 2., 0.],
               [2., 4., 1.],
               [1., 3., 2.],
               [-1., -2., 4.],
               [-1., -2., 5.],
               [1., 2., 6.]])

mid = arr.shape[0]//2
np.vstack([arr[mid:],arr[:mid]])

array([[-1., -2.,  4.],
       [-1., -2.,  5.],
       [ 1.,  2.,  6.],
       [ 1.,  2.,  0.],
       [ 2.,  4.,  1.],
       [ 1.,  3.,  2.]])


In [ ]:
shp = 2, arr.shape[0]//2, arr.shape[1] #2,3,3
strd = arr.strides[0]*3, arr.strides[0], arr.strides[1] #72,24,8 bytes

chunks = np.lib.stride_tricks.as_strided(arr, shape=shp, strides=strd)
np.vstack([chunks[1],chunks[0]])

In [ ]:
big_list=[np.array([[1., 1., 2.], [1., 1., 1.9], [1., 1., 5.2]]),
          np.array([[1., 3., 5.1], [0., 0., 1.2], [1., 1., 1.4]])]

small_list= [np.array([[-1., -1., -5.]]),
             np.array([[-1., -1., -1.], [0., -2., -0.5]])]

In [ ]:
merged= [np.array([[1., 1., 2.], [1., 1., 1.9], [-1., -1., -5.], [1., 1., 5.2]]),
         np.array([[1., 3., 5.1], [-1., -1., -1.], [0., -2., -0.5], [0., 0., 1.2], [1., 1., 1.4]])]

In [ ]:
merged = []
for i in range(len(big_list)):
    idx = np.argwhere(np.abs(np.diff(big_list[i][:,2]))>3)[0]+1
    m = np.insert(big_list[i], idx, small_list[i], axis=0)
    merged.append(m)
    
merged

In [ ]:
np.argmax(np.abs(np.diff(big_list[i][:,2])))+1

In [ ]:
big_list[i][:,2]

In [ ]:
idx = np.argwhere(np.abs(np.diff(big_list[0][:,2]))>3)[0]+1
idx

In [ ]:
df = pd.read_clipboard()
df

In [ ]:
df.groupby(['Document','Date','Key']).transform(lambda x: x['Schedule'])

In [ ]:
2.3, 2.7, 1.7, 0.5, 0.1, 0.6, 1.6

In [ ]:
arr = np.array([0.1, 1, 1.2, 0.5, -0.3, -0.2, 0.1, 0.5, 1])

arr

In [ ]:
arr.shape

In [ ]:
arr = np.array([0.1, 1, 1.2, 0.5, -0.3, -0.2, 0.1, 0.5, 1])
w = 3  #rolling window
arr[arr<0]=0
shape = arr.shape[0]-w+1, w
strides = arr.strides[0]*2, arr.strides[0]
rolling = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)
#rolling_sum = np.sum(rolling, axis=1)
print(rolling)

In [ ]:
np.correlate(arr.clip(0), np.ones(3), mode='valid')

In [ ]:
df = pd.read_clipboard()
df

In [ ]:
'foo//,'.replace('\\,',',')

In [ ]:
def fix(s):
    if s['B']=='cherry':
        s['A']=s['A'].replace('//,',',')
    return s

print(df.apply(fix, axis=1))

In [ ]:
df['qty'][4]

In [ ]:
df = pd.read_clipboard('\s\s+')

def fix(row):
    if pd.isnull(row['qty']):
        row['qty']=row['Item'][-1:]
        row['Item']=row['Item'][:-1].strip()
    return row

print(df.apply(fix, axis=1))

In [ ]:
np.diag()

In [ ]:
X = np.array([37., 42., 31., 27., 37.])
Y = np.array([52., 57., 62., 68., 69.])
XY = np.stack([X,Y]).T

In [ ]:
%%timeit
np.sum(np.sqrt(np.sum(np.square(np.diff(np.vstack([XY,XY[0]]), axis=0)), axis=-1)))

In [ ]:
%%timeit
pairwise = np.sqrt(np.sum(np.square(np.subtract(XY[:,None,:],XY[None,:,:])), axis=-1))
total = np.sum(np.diag(pairwise,k=1))+pairwise[0,-1]

In [ ]:
%%timeit


sum1 = euclidean(XY[0],XY[-1])


for i in range(len(XY)-1):
    sum1 += euclidean(XY[i],XY[i+1])

In [ ]:
%%timeit

from functools import reduce
from operator import add

def euclidean_distance(p1, p2): 
     return sum((p1 - p2) ** 2) ** .5
reduce(add, [euclidean_distance(p1, p2) for p1, p2 in zip(XY, XY[1:])])

In [ ]:
%%timeit

# find the differences, prepend the last value at the front
diff = np.diff(XY, axis=0, prepend=XY[-1].reshape((1, -1)))

# raise to the power of 2 and sum
ss = np.power(diff, 2).sum(axis=1)

# find the square root and sum
res = np.sqrt(ss).sum()

In [ ]:
%%timeit

np.linalg.norm(XY - np.roll(XY, -1, axis=0), axis=1).sum()

In [ ]:
#%%timeit
diff = np.diff(XY, axis=0)
# [[5. 5.]] (42 - 37) (57 - 52)

ss = np.power(diff, 2).sum(axis=1)
# [50.] 5^2 + 5^2

res = np.sqrt(ss).sum()
# 7.0710678118654755 

res

In [ ]:
pairwise

In [ ]:
from scipy.spatial.distance import euclidean

X = np.array([37., 42., 31., 27., 37.])

Y = np.array([52., 57., 62., 68., 69.])
XY = np.array((X, Y)).T    
sum1 = euclidean(XY[0],XY[-1])


for i in range(len(XY)-1):
    sum1 += euclidean(XY[i],XY[i+1])

In [ ]:
sum1

In [ ]:
X = np.random.random(1000)
Y = np.random.random(1000)

In [ ]:
def distance_charel(X, Y):
    N = len(X)
    T = 0
    oldx, oldy = X[-1], Y[-1]
    for x, y in zip(X, Y):
        T += np.linalg.norm((np.array([x,y])-np.array([oldx,oldy])))
        oldx = x
        oldy = y
    return T

def distance_dani(X, Y):
    XY = np.array((X, Y)).T
    diff = np.diff(XY, axis=0, prepend=XY[-1].reshape((1, -1)))
    ss = np.power(diff, 2).sum(axis=1)
    res = np.sqrt(ss).sum()
    return res

def distance_akshay(X, Y):
    XY = np.array((X, Y)).T
    pairwise = np.sqrt(np.sum(np.square(np.subtract(XY[:,None,:],XY[None,:,:])), axis=-1))
    return np.sum(np.diag(pairwise,k=1))+pairwise[0,-1]
    #return np.sum(np.sqrt(np.sum(np.square(np.diff(np.vstack([XY,XY[0]]), axis=0)), axis=-1)))

def distance_gwang(X, Y):
    XY = np.array((X, Y)).T
    return sum([sum((p1 - p2) ** 2) ** .5 for p1, p2 in zip(XY, XY[1:])])

def d

print(distance_charel(X, Y))
print(distance_dani(X, Y))
print(distance_akshay(X, Y))
print(distance_gwang(X, Y))  # I think it misses the distance between last and first element
%timeit distance_charel(X, Y)
%timeit distance_dani(X, Y)
%timeit distance_akshay(X, Y)
%timeit distance_gwang(X, Y)

In [ ]:
import numpy as np

m = np.array([[5,3,  6,7,  3,7],
              [5,4,  5,1,  4,5],
              [5,4,  2,4,  4,6],
              [2,2,  2,3,  8,5],
              [2,7,  8,7,  1,2],
              [2,7,  8,7,  3,2],
              [2,7,  8,7,  4,2]]) 

n = np.array([[1,3,  6,7,  1,12],
              [2,4,  2,9,  4,9],
              [1,5,  5,12, 9,1],
              [5,4,  5,6,  9,5],
              [5,4,  1,4,  1,5],
              [5,4,  1,7,  9,5],
              [5,4,  1,5,  4,11]])


mm = m.reshape(m.shape[0],-1,2) #(7,3,2)
nn = n.reshape(m.shape[0],-1,2) #(7,3,2)

#broadcast((7,3,1,2,1), (7,1,3,1,2)) -> (7,3,3,2,2) -> (7,3,3)
matches_m = np.any(mm[:,:,None,:,None] == mm[:,None,:,None,:], axis=(-1,-2))  #(7,3,3)
matches_n = np.any(nn[:,:,None,:,None] == nn[:,None,:,None,:], axis=(-1,-2))  #(7,3,3)

mask = ~np.eye(mm.shape[1], dtype=bool)[None,:]  #(1,3,3)

is_valid1 = np.all(np.any(matches_m&mask, axis=-1), axis=-1)  #(7,)
is_valid2 = np.all(~(matches_m^matches_n)|matches_n, axis=(-1,-2)) #(7,)

m[is_valid1 & is_valid2]

Apply the same first 4 steps to get the matches matrix (7,3,3) for n.

Here, any match that exists in m MUST exist in n, but any match that exists in n is not needed in m. Therefore, you can simply use the match matrix of m as a boolean index for n to get where all match_m is True, is match_n True as well.

This gives you the TEST2.

In [ ]:
is_valid2

In [ ]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])


~(a^b)|b

array([ True,  True, False,  True])

#array([ True, True,  False,  True])

#If a and b have match then True
#If a doesnt have match but b has then False
#If a has match but b doesnt have match then True

In [ ]:
b = matches_n[0]
b

In [ ]:
a = matches_m[0]
a

In [ ]:
a==(a&b|b)

In [ ]:
np.any((a&b|b)&mask[0], axis=-1)

In [ ]:
matches_m[3]

In [ ]:
matches_n[3]

In [ ]:
matches_n.flatten()

In [ ]:
x = 5
y = 7

In [ ]:
points = [
    [[x,y], [x,y], [x,y]],
    [[x,y], [x,y], [x,y], [x,y], [x,y]],
    [[x,y]]
]

weights = [1, 2, 3]

[[k+[weights[i]] for k in j] for i,j in enumerate(points)]

[[[5, 7, 1], [5, 7, 1], [5, 7, 1]],
 [[5, 7, 2], [5, 7, 2], [5, 7, 2], [5, 7, 2], [5, 7, 2]],
 [[5, 7, 3]]]

In [ ]:
l = [[1, 4, 5], [4, 6, 8], [8, 3, 10]]

for i in l:
    print(i)
    
[1, 4, 5]
[4, 6, 8]
[8, 3, 10]

import numpy as np
print(np.array(l))
[[ 1  4  5]
 [ 4  6  8]
 [ 8  3 10]]

In [ ]:
list1 = [3, 54, 11, 17]
list2 = [54, 3, 23, 17, 11, 50, 17]

x = [i for i in list2 if i in list1]
x

In [ ]:
rawdata = {'portfolio': ['port1', 'port2', 'port1', 'port2'],
        'portfolioname': ['portfolioone', 'portfoliotwo', 'portfolioone', 'portfoliotwo'],
        'date': ['04/12/2020', '04/12/2020', '04/12/2020', '04/12/2020'],
        'code': ['ABC', 'ABC', 'XYZ', 'XYZ'],
        'quantity': [2, 3, 10, 11],
        'price': [1.5, 1.5, 0.2, 0.2],
        'value': [3, 4.5, 2, 2.2],
        'weight': [.6, .67, .4, .328]}

df1 = pd.DataFrame(rawdata)
df1

In [ ]:
def pfix(s):
    if 

In [ ]:
word2int = {'one': 1, 
             'two': 2, 
             'three': 3, 
             'four': 4, 
             'five': 5, 
             'six': 6, 
             'seven': 7, 
             'eight': 8, 
             'nine': 9, 
             'zero' : 0}

int2word = {v:k for k,v in word2int.items()}

g = {'portfolio':lambda x: 'port'+str(sum([int(i[-1]) for i in x])),
     'portfolioname':lambda x: 'portfolio'+int2word.get(sum([word2int.get(i[9:]) for i in x])),
     'date':'first',
     'quantity':'sum',
     'price':'mean',
     'value':'sum',
     'weight':'mean'}

df1.groupby(['code']).agg(g).reset_index()

  code portfolio   portfolioname        date  quantity  price  value  weight
0  ABC     port3  portfoliothree  04/12/2020         5    1.5    7.5   0.635
1  XYZ     port3  portfoliothree  04/12/2020        21    0.2    4.2   0.364

In [ ]:
finisheddata = {'portfolio': ['port3', 'port3'],
        'portfolioname': ['portfoliothree', 'portfoliothree'],
        'date': ['04/12/2020', '04/12/2020'],
        'code': ['ABC', 'XYZ'],
        'quantity': [5, 21],
        'price': [1.5, 0.2],
        'value': [7.5, 4.2],
        'weight': [.64, .36]}

df2 = pd.DataFrame(finisheddata)
df2

In [ ]:

import tensorflow as tf
inp = tf.keras.layers.Input(shape=(1,))
x = tf.keras.layers.Reshape((-1,1))(inp)
#x = tf.expand_dims(inp, axis=-1)
#x = inp[...,tf.newaxis]
decoder_input = inp
output = tf.concat([inp, decoder_input], 1)
model = tf.keras.models.Model(inp, output)

model.summary()

In [ ]:
import math
 
shades = ('.',':','!','*','o','e','&','#','%','@')
 
def normalize(v):
    len = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2)
    return (v[0]/len, v[1]/len, v[2]/len)
 
def dot(x,y):
    d = x[0]*y[0] + x[1]*y[1] + x[2]*y[2]
    return -d if d < 0 else 0
 
def draw_sphere(r, k, ambient, light):
    for i in range(int(math.floor(-r)),int(math.ceil(r)+1)):
        x = i + 0.5
        line = ''
 
        for j in range(int(math.floor(-2*r)),int(math.ceil(2*r)+1)):
            y = j/2 + 0.5
            if x*x + y*y <= r*r:
                vec = normalize((x,y,math.sqrt(r*r - x*x - y*y)))
                b = dot(light,vec)**k + ambient
                intensity = int((1-b)*(len(shades)-1))
                line += shades[intensity] if 0 <= intensity < len(shades) else shades[0]
            else:
                line += ' '
 
        print(line)
 
light = normalize((30,30,-50))
draw_sphere(20,4,0.1, light)

In [ ]:
X, y = np.random.random((10,5)), np.random.random((10,))

In [ ]:
from tensorflow.keras import layers, Model, callbacks

class CustomCallback(callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(' ')
        print(' ')
        print(model.layers[1].get_weights())
        

inp = layers.Input((5,))
x = layers.Dense(3)(inp)
out = layers.Dense(1)(x)

model = Model(inp, out)

model.compile(loss='MAE',metrics=['accuracy'])
model.fit(X,y,callbacks=[CustomCallback()], epochs=3)

In [ ]:
from scipy import spatial
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-50")

In [ ]:
model.most_similar("cat")

In [ ]:
model['cat']

In [ ]:
from scipy import spatial
import gensim.downloader as api

model = api.load("glove-wiki-gigaword-50") #choose from multiple models https://github.com/RaRe-Technologies/gensim-data

s0 = 'Mark zuckerberg owns the facebook company'
s1 = 'Facebook company ceo is mark zuckerberg'
s2 = 'Microsoft is owned by Bill gates'
s3 = 'How to learn japanese'

def preprocess(s):
    return [i.lower() for i in s.split()]

def get_vector(s):
    return np.sum(np.array([model[i] for i in preprocess(s)]), axis=0)


print('s0 vs s1 ->',1 - spatial.distance.cosine(get_vector(s0), get_vector(s1)))
print('s0 vs s2 ->', 1 - spatial.distance.cosine(get_vector(s0), get_vector(s2)))
print('s0 vs s3 ->', 1 - spatial.distance.cosine(get_vector(s0), get_vector(s3)))

In [ ]:
get_vector(s1)

In [ ]:
(84,36) (84,36,210,45)

In [ ]:
a = np.random.random((84,36))
b = np.random.random((84,36,210,45))

c = b.transpose(2,3,0,1) + a
c = c.transpose(2,3,0,1)
c.shape

(84, 36, 210, 45)

c = a[...,None, None] + b
c.shape

In [ ]:
import numpy as np

In [ ]:
c = a[...,None, None] + b
c.shape

In [ ]:
a = np.random.random((840,36))
b = np.random.random((840,36,210,45))

In [ ]:
%%timeit
(b.transpose(2,3,0,1) + a).transpose(2,3,0,1)

In [ ]:
%%timeit
a[...,None, None] + b

In [ ]:
import re

genome = "GCTAGCTAGCTAGCTGACGCGATCGATGCTAGTTTCGGTGCGCTtAAAAAAGCTTGCATGAAGGCTAGCTA"
primer = "AGCTGANNNNNTCGATGC"

reg = '[A-Z]+'.join([i for i in primer.split('N') if len(i)>0])

idx = re.search(reg, genome).span()

print(genome)
print(''.join((['_']*idx[0])+list(primer)+(['_']*(len(genome)-idx[1]))))

In [ ]:
idx

In [2]:
for i in range(1,int(input())):
    print(*[i]*i, sep = "") 

4
1
22
333


In [4]:
import numpy as np

In [5]:
A = np.random.random((10,10))

In [7]:
covariance = np.matmul(A, np.transpose(A)) / (np.matmul(np.dot(A, np.transpose(A))))
covariance

ValueError: invalid number of arguments

In [8]:
np.cov(A)

array([[ 0.10853557,  0.01929256,  0.00954158, -0.00794658, -0.00791169,
         0.00611973,  0.01565745,  0.03271472,  0.00861337, -0.01697939],
       [ 0.01929256,  0.07967162, -0.00217917, -0.04906408,  0.01744324,
         0.01606904,  0.01117259, -0.02408023,  0.03616033, -0.01818961],
       [ 0.00954158, -0.00217917,  0.1065416 ,  0.00445259, -0.00587653,
         0.02932955, -0.01809237, -0.04799165, -0.00610039,  0.03159512],
       [-0.00794658, -0.04906408,  0.00445259,  0.10712343, -0.06236525,
         0.00795802, -0.06050063,  0.02553102, -0.02010926,  0.01578749],
       [-0.00791169,  0.01744324, -0.00587653, -0.06236525,  0.07659316,
        -0.00845212,  0.01726666, -0.04445887,  0.00892494,  0.026926  ],
       [ 0.00611973,  0.01606904,  0.02932955,  0.00795802, -0.00845212,
         0.09131461, -0.00081991,  0.01987169,  0.01976261, -0.0185913 ],
       [ 0.01565745,  0.01117259, -0.01809237, -0.06050063,  0.01726666,
        -0.00081991,  0.09821293, -0.00377872