# Week 2

###  Vectorization

In [2]:
import numpy as np
import time

In [5]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [19]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version : ",str(1000*(toc-tic)),"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Non Vectorized version : ",str(1000*(toc-tic)),"ms")

249753.357109
Vectorized version :  1.505136489868164 ms
249753.357109
Non Vectorized version :  616.1375045776367 ms


### Broadcasting

In [32]:
A = np.array([[144,0,11,55],
              [22,66,12,76],
              [56,12,55,90]])
A.shape

(3, 4)

In [37]:
#Lets say we wanna sum the column vectors and then create each value as a % of its column

#Take sum of each column vector and store in a row vector called sums
#Axis = 0 is vertical, Axis = 1 is horizontal
sums = A.sum(axis=0)

#Divide A matrix with reshaped sums
percentage = 100*A/(sums.reshape(1,4))
print(percentage)

[[ 64.86486486   0.          14.1025641   24.88687783]
 [  9.90990991  84.61538462  15.38461538  34.38914027]
 [ 25.22522523  15.38461538  70.51282051  40.7239819 ]]


### Notes on Python/Numpy

In [53]:
a = np.random.randn(5)
print(a)
a.shape

#This creates a rank 1 array, not worth using since its effects are strange

[-1.09999395  0.1273466   1.102039   -0.82667187 -1.83105466]


(5,)

In [54]:
#Instead use following for getting a matrix
a = np.random.randn(5,1)
print(a)
a.shape

#This creates a column vector

[[-0.54063534]
 [-1.78415232]
 [ 1.77694535]
 [-0.20465918]
 [-0.62250323]]


(5, 1)

In [55]:
print(a.T)

#This creates a row vector

[[-0.54063534 -1.78415232  1.77694535 -0.20465918 -0.62250323]]


In [50]:
print(np.dot(a,a.T))

[[ 0.1849679   0.43068752 -0.12684213  0.10236518  0.72839086]
 [ 0.43068752  1.00283205 -0.29534488  0.23835165  1.69601781]
 [-0.12684213 -0.29534488  0.08698226 -0.07019714 -0.49949559]
 [ 0.10236518  0.23835165 -0.07019714  0.05665107  0.40310703]
 [ 0.72839086  1.69601781 -0.49949559  0.40310703  2.8683531 ]]


In [59]:
#Converting a rank 1 array to a matrix

b = np.random.randn(5)
print(b,b.shape)

c = b.reshape(5,1)
print(c,c.shape)

[-1.09646521  0.73289268  0.61928838 -0.01740936 -0.80460874] (5,)
[[-1.09646521]
 [ 0.73289268]
 [ 0.61928838]
 [-0.01740936]
 [-0.80460874]] (5, 1)


In [5]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 1.14224626,  0.72052709,  1.54459408],
       [-0.35578058, -1.77117135,  1.34289895],
       [ 0.0643698 ,  0.04619388,  0.09529738]])