In [ ]:
from multiprocessing import Pool

In [ ]:
def some_heavy_computation(b):
    return (10 - b)**5

In [ ]:
n = 4

In [ ]:
p = Pool()

In [ ]:
p.map(some_heavy_computation,[1,5,7,2])

In [ ]:
inp.shape

In [11]:
import pdb

In [52]:
mat = np.array([[0, 1, 0],
                [0, 0, 1],
                [1, 1, 1],
                [0, 0, 1],
                [0, 0, 1]])

In [23]:
state = 0

for row in mat:
    print('row : ',row)
    print('state: ', state)
    if set(row) == {1}:
        state = 1
    elif set(row) == {0}:
        state = 0
    else:
        row[:] = state
    print(mat)
    print('----------')

row :  [0 1 0]
state:  0
[[0 0 0]
 [0 0 1]
 [1 1 1]
 [0 0 1]
 [0 0 1]]
----------
row :  [0 0 1]
state:  0
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [0 0 1]]
----------
row :  [1 1 1]
state:  0
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 1]
 [0 0 1]]
----------
row :  [0 0 1]
state:  1
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [0 0 1]]
----------
row :  [0 0 1]
state:  1
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
----------


In [9]:
mat

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
import time
import numpy as np

mat = np.random.randint(2, size=(100000,100))

In [53]:
mat = np.array([[0, 1, 0],
                [0, 0, 1],
                [1, 1, 1],
                [0, 0, 1],
                [0, 0, 1]])

0.00010800361633300781  sec


[1, 1, 0, 1, 1]

# Base line

In [75]:
mat = np.random.randint(2, size=(100000,100))

start = time.time()

def compute(mat):
    state = 0
    
    for row in mat:
        if set(row) == {1}:
            state = 1
        elif set(row) == {0}:
            state = 0
        else:
            row[:] = state
    return mat

results = compute(mat)

end = time.time()
print(end-start,' sec')

results.shape

1.7265353202819824  sec


(100000, 100)

# Boolean approach

In [78]:
mat = np.random.randint(2, size=(100000,100))

start = time.time()
    
def flags(row):
    flg = int(len(set(row))>1)
    return flg

def 
    
results = [flags(i) for i in mat]

end = time.time()
print(end-start,' sec')
len(results)

0.8579797744750977  sec


100000