# Non Negative Matrix Factorization

Matrix factorization is an approach to decompose a matrix into 

In [195]:
from sklearn.decomposition import NMF
import numpy as np
import pandas as pd

In [250]:
list_movies = ['inception',        #thrill
               'gladiator',        #fantasy
               'godfather',        #conversations
               'pulp fiction',     #conversations
               '12 angry men',     #conversations
               'dark knight',      #thrill
               'fight club',       #thrill
               'lotr']             #fantasy


#So i have 3 types of features that I want to extract as 'topics'

users = ['a',  #prefers thrill only
         'b',  #prefers everything
         'c',  #prefers conversations and fantasy
         'd',  #prefers fantasy only
         'e',  #prefers thrill only
         'f',  #prefers conversation only
         'g']  #prefers thrill and fantasy

movie_preference = {'a':[4.5, 1.5, 0.0, 1.0, 0.0, 5.0, 4.5, 0.0],
                    'b':[4.5, 5.0, 4.0, 4.7, 4.6, 4.9, 4.4, 4.2],
                    'c':[0.0, 4.5, 4.2, 4.2, 4.6, 1.1, 2.0, 5.0],
                    'd':[0.0, 4.6, 0.0, 1.3, 0.0, 0.0, 2.0, 4.9],
                    'e':[4.2, 0.0, 1.1, 2.2, 2.8, 5.0, 4.9, 0.0],
                    'f':[0.0, 0.0, 4.5, 4.2, 4.9, 0.0, 0.0, 2.1],
                    'g':[4.6, 4.3, 0.0, 0.0, 0.0, 4.5, 4.5, 4.9]
                   }

ratings_df = pd.DataFrame(movie_preference).T
ratings_df.columns = list_movies
ratings_df

inception  gladiator  godfather  pulp fiction  12 angry men  dark knight  \
a        4.5        1.5        0.0           1.0           0.0          5.0   
b        4.5        5.0        4.0           4.7           4.6          4.9   
c        0.0        4.5        4.2           4.2           4.6          1.1   
d        0.0        4.6        0.0           1.3           0.0          0.0   
e        4.2        0.0        1.1           2.2           2.8          5.0   
f        0.0        0.0        4.5           4.2           4.9          0.0   
g        4.6        4.3        0.0           0.0           0.0          4.5   

   fight club  lotr  
a         4.5   0.0  
b         4.4   4.2  
c         2.0   5.0  
d         2.0   4.9  
e         4.9   0.0  
f         0.0   2.1  
g         4.5   4.9

In [251]:
mat = np.array(ratings_df)
print(mat.shape)
mat

(7, 8)


array([[4.5, 1.5, 0. , 1. , 0. , 5. , 4.5, 0. ],
       [4.5, 5. , 4. , 4.7, 4.6, 4.9, 4.4, 4.2],
       [0. , 4.5, 4.2, 4.2, 4.6, 1.1, 2. , 5. ],
       [0. , 4.6, 0. , 1.3, 0. , 0. , 2. , 4.9],
       [4.2, 0. , 1.1, 2.2, 2.8, 5. , 4.9, 0. ],
       [0. , 0. , 4.5, 4.2, 4.9, 0. , 0. , 2.1],
       [4.6, 4.3, 0. , 0. , 0. , 4.5, 4.5, 4.9]])

In [252]:
components = 3

nmf = NMF(n_components=3, random_state=1, alpha=0.1, l1_ratio=0.5, init='nndsvd')

In [253]:
user_vectors = nmf.fit_transform(mat)
print(user_vectors.shape)
user_vectors

(7, 3)


array([[2.05026266, 0.00879439, 0.18553659],
       [1.80817707, 1.93961494, 1.55007755],
       [0.17647809, 1.99112794, 1.74519355],
       [0.01367688, 0.12157961, 1.91384047],
       [2.05153774, 0.8519357 , 0.        ],
       [0.        , 2.16825726, 0.24428509],
       [1.75102874, 0.        , 1.68964144]])

In [254]:
movie_vectors = nmf.components_.T
print(movie_vectors.shape)
movie_vectors

(8, 3)


array([[2.25923564, 0.        , 0.07446867],
       [0.29854598, 0.        , 2.47458955],
       [0.        , 2.0248213 , 0.        ],
       [0.22912065, 1.94149548, 0.22410185],
       [0.1297229 , 2.293077  , 0.        ],
       [2.42707714, 0.10483078, 0.12542259],
       [2.05865751, 0.        , 0.75926566],
       [0.        , 0.36514407, 2.53593563]])

In [255]:
# what rating will D give to Inception.

inception_vector = movie_vectors[0]
print('inception vector ->', inception_vector)

d_vector = user_vectors[3]
print('d vector ->', d_vector)

inception vector -> [2.25923564 0.         0.07446867]
d vector -> [0.01367688 0.12157961 1.91384047]


In [256]:
# New R

nR = pd.DataFrame(np.dot(user_vectors, movie_vectors.T), index = users, columns=list_movies)
nR

inception  gladiator  godfather  pulp fiction  12 angry men  dark knight  \
a   4.645843   1.071225   0.017807      0.528411      0.286132     5.000338   
b   4.200530   4.375630   3.927374      4.527420      4.682248     4.786331   
c   0.528668   4.371325   4.031678      4.297302      4.588703     0.855944   
d   0.173420   4.740053   0.246177      0.668075      0.280566     0.285979   
e   4.634907   0.612478   1.725018      2.124079      2.219686     5.068549   
f   0.018192   0.604505   4.390333      4.264406      4.971981     0.257939   
g   4.081812   4.703932   0.000000      0.779849      0.227149     4.461801   

   fight club      lotr  
a    4.361660  0.473720  
b    4.899338  4.639136  
c    1.688373  5.152747  
d    1.481269  4.897770  
e    4.223414  0.311079  
f    0.185477  1.411218  
g    4.887655  4.284822

In [257]:
ratings_df

inception  gladiator  godfather  pulp fiction  12 angry men  dark knight  \
a        4.5        1.5        0.0           1.0           0.0          5.0   
b        4.5        5.0        4.0           4.7           4.6          4.9   
c        0.0        4.5        4.2           4.2           4.6          1.1   
d        0.0        4.6        0.0           1.3           0.0          0.0   
e        4.2        0.0        1.1           2.2           2.8          5.0   
f        0.0        0.0        4.5           4.2           4.9          0.0   
g        4.6        4.3        0.0           0.0           0.0          4.5   

   fight club  lotr  
a         4.5   0.0  
b         4.4   4.2  
c         2.0   5.0  
d         2.0   4.9  
e         4.9   0.0  
f         0.0   2.1  
g         4.5   4.9

In [258]:
#lets calculate the error

E = (nR - ratings_df)**2

In [259]:
E

inception  gladiator  godfather  pulp fiction  12 angry men   dark knight  \
a   0.021270   0.183848   0.000317      0.222396      0.081872  1.142670e-07   
b   0.089682   0.389838   0.005275      0.029784      0.006765  1.292057e-02   
c   0.279490   0.016557   0.028332      0.009468      0.000128  5.956327e-02   
d   0.030075   0.019615   0.060603      0.399329      0.078717  8.178396e-02   
e   0.189144   0.375130   0.390647      0.005764      0.336765  4.699024e-03   
f   0.000331   0.365427   0.012027      0.004148      0.005181  6.653251e-02   
g   0.268519   0.163161   0.000000      0.608164      0.051596  1.459160e-03   

   fight club      lotr  
a    0.019138  0.224411  
b    0.249338  0.192840  
c    0.097111  0.023332  
d    0.269081  0.000005  
e    0.457769  0.096770  
f    0.034402  0.474421  
g    0.150277  0.378444

In [260]:
np.average(E)

0.1361368283583241

In [272]:
new_data = np.array([[4.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]])

In [273]:
nmf.transform(new_data)

array([[0.6990525, 0.       , 0.       ]])