In [72]:
import itertools
import pandas as pd
import numpy as np

In [73]:
hour = np.arange(0,24)
day = np.arange(0,30)
month = np.arange(0,12)
product = ['A','B','C','D']

In [74]:
df = pd.DataFrame(list(itertools.product(month, day, hour, product)), columns=['month','day','hour','product'])

In [75]:
df['vol'] = np.random.randint(0,40, size=df.shape[0])
df['price'] = -1
df['discount'] = np.random.uniform(0,0.2,size=df.shape[0])

In [76]:
df['price'].loc[df['product']=='A'] = 10
df['price'].loc[df['product']=='B'] = 5
df['price'].loc[df['product']=='C'] = 3
df['price'].loc[df['product']=='D'] = 8

/Users/akshay/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [77]:
df['sale'] = df['vol']*df['price']*(1-df['discount'])

month  day  hour product  vol  price  discount        sale
0          0    0     0       A   36     10  0.175162  296.941507
4          0    0     1       A   28     10  0.015685  275.608180
8          0    0     2       A   11     10  0.184631   89.690594
12         0    0     3       A    0     10  0.072765    0.000000
16         0    0     4       A   34     10  0.166528  283.380432
...      ...  ...   ...     ...  ...    ...       ...         ...
34540     11   29    19       A   29     10  0.073041  268.818027
34544     11   29    20       A    7     10  0.010664   69.253511
34548     11   29    21       A   10     10  0.091837   90.816259
34552     11   29    22       A   27     10  0.138411  232.629122
34556     11   29    23       A   12     10  0.164978  100.202636

[8640 rows x 8 columns]

In [82]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [93]:
ddf = df[df['product']=='A']
X = ddf[['month','day','hour','discount']]
y = ddf['sale']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print([i.shape for i in [X_train, X_test, y_train, y_test]])

rf = RandomForestRegressor()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

[(6912, 4), (1728, 4), (6912,), (1728,)]


-0.11394229803183764

NameError: name 'k' is not defined

In [96]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(2,2,4)

In [97]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [100]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).reshape(2,2,4)
np.max(arr.reshape(2,-1),-1)

array([ 8, 16])

In [155]:
df = pd.DataFrame({'Class': [1, 2], 'Students': ['A,B,C,D', 'E,A,C']})
df

Class Students
0      1  A,B,C,D
1      2    E,A,C

In [138]:
import itertools

df['Students'] = df['Students'].str.split(',')
df = df.explode('Students')

In [171]:
list(itertools.product(*[list(df.loc[df['Class']==i,'Students'])[0].split(',') for i in df['Class'].unique()]))

[('A', 'E'),
 ('A', 'A'),
 ('A', 'C'),
 ('B', 'E'),
 ('B', 'A'),
 ('B', 'C'),
 ('C', 'E'),
 ('C', 'A'),
 ('C', 'C'),
 ('D', 'E'),
 ('D', 'A'),
 ('D', 'C')]

In [147]:
[list(df.groupby('Class')['Students'])[i][1] for i in len(df['Class'].unique())]

IndexError: list index out of range

In [140]:
df

Class Students
0      1        A
0      1        B
0      1        C
0      1        D
1      2        E
1      2        A
1      2        C

In [130]:
[','.join(i) for i in list(itertools.combinations(df['Students'],2))]

['A,B',
 'A,C',
 'A,D',
 'A,E',
 'A,A',
 'A,C',
 'B,C',
 'B,D',
 'B,E',
 'B,A',
 'B,C',
 'C,D',
 'C,E',
 'C,A',
 'C,C',
 'D,E',
 'D,A',
 'D,C',
 'E,A',
 'E,C',
 'A,C']

In [209]:
train = pd.DataFrame(np.random.random(size=(100,1)), columns=['Age'])
train['class'] = np.random.randint(0,4,size=(train.shape[0],))
test = pd.DataFrame(np.random.random(size=(20,1)), columns=['Age'])
test['class'] = np.random.randint(0,4,size=(test.shape[0],))

#dummy missing
idx = np.random.randint(0, test.shape[0], size=10)
test['Age'].iloc[idx] = np.nan

In [215]:
meanAgeTrain = train.groupby(['class'])['Age'].mean()
meanAgeTrain

class
0    0.423736
1    0.565016
2    0.552762
3    0.433295
Name: Age, dtype: float64

In [212]:
test[test['Age'].isna()]

Age  class
1   NaN      0
3   NaN      3
5   NaN      0
10  NaN      1
13  NaN      2
15  NaN      3
16  NaN      2
17  NaN      0

In [199]:
for df in [train, test]:
    df['Age'] = df['Age'].fillna(meanAgeTrain)

In [218]:
train

Age  class
0   0.067944      2
1   0.823636      2
2   0.772422      3
3   0.726082      2
4   0.058049      0
..       ...    ...
95  0.195786      3
96  0.982970      1
97  0.313166      3
98  0.251548      1
99  0.179563      0

[100 rows x 2 columns]

In [ ]:
Age      0.449318
class    1.000000
Name: 0, dtype: float64

In [225]:
test.apply(lambda x: x.Age , axis=1)

Age  class
0   0.449318    1.0
1        NaN    0.0
2   0.596808    0.0
3        NaN    3.0
4   0.435593    0.0
5        NaN    0.0
6   0.042038    0.0
7   0.561412    2.0
8   0.131966    0.0
9   0.952183    0.0
10       NaN    1.0
11  0.326681    1.0
12  0.729088    1.0
13       NaN    2.0
14  0.463054    1.0
15       NaN    3.0
16       NaN    2.0
17       NaN    0.0
18  0.542166    1.0
19  0.297670    3.0

In [207]:
test

Age  class
0   0.358718      0
1   0.921489      3
2   0.832573      2
3   0.097872      2
4   0.589739      2
5   0.508790      3
6   0.781734      1
7   0.422133      1
8   0.508790      2
9   0.664423      2
10  0.676395      3
11  0.760232      1
12  0.768031      3
13  0.501769      3
14  0.426808      1
15  0.462139      3
16  0.446916      1
17  0.446916      0
18  0.446916      3
19  0.203988      0

In [203]:
meanAgeTrain

0     0.589739
1     0.462139
2     0.462139
3     0.589739
4     0.589739
        ...   
95    0.508790
96    0.446916
97    0.446916
98    0.446916
99    0.589739
Name: Age, Length: 100, dtype: float64

In [202]:
test

Age  class
0   0.358718      0
1   0.921489      3
2   0.832573      2
3   0.097872      2
4   0.589739      2
5   0.508790      3
6   0.781734      1
7   0.422133      1
8   0.508790      2
9   0.664423      2
10  0.676395      3
11  0.760232      1
12  0.768031      3
13  0.501769      3
14  0.426808      1
15  0.462139      3
16  0.446916      1
17  0.446916      0
18  0.446916      3
19  0.203988      0

In [227]:
df = pd.read_clipboard('\s\s+')

In [239]:
for peptide in peptides:
    model=LogisticRegression()
    model.fit(X_train[peptide], y_train)
    score = model.score(X_test[peptide], y_test)
    y_pred=model.predict(X_test[peptide])
    acc_score = accuracy_score(y_test, y_pred)
    LR_scores.append(peptide,acc_score)
    
    #Classification Report
    print (classification_report(y_test,y_pred))
    
    #Confusion Matrix
    cnf_matrix = confusion_matrix(y_test,y_pred)
    print(cnf_matrix)
    
    #ROC_AUC Curves
    y_predict_proba = model.predict_proba(X_test[peptide])
    probabilities = np.array(y_predict_proba)[:, 1]
    fpr, tpr, thresholds = roc_curve(y_test, probabilities, pos_label=1)
    roc_auc = auc(fpr, tpr)
    logit_roc_auc = roc_auc_score(y_test, model.predict(X_test[peptide]))

array([[ 5.67],
       [ 7.88],
       [15.5 ],
       [ 6.52],
       [ 4.53]])