In [5]:
weight = 5.6
height = 66.7

BMI = weight/height**2

print(BMI)
type(BMI)

0.0012587409443703932


float

In [7]:
print(5+2)
print('ab'+"ba")

7
abba


In [10]:
saving = 100
factor = 1.1

print("I saved $"+str(saving)+" in a bank for 7 years and now i have $" +str(saving*factor**7)+", Awesome!")

I saved $100 in a bank for 7 years and now i have $194.87171000000012, Awesome!


In [19]:
sister = "liz"

#Built in functions
type(sister)
len(sister)

#Methods, associated with different objects only
sister = sister.replace("z","sa")
sister.index("lisa")

0

In [23]:
room = "poolhouse"
room_up = room.upper()
print(room.count("o"))
print(room_up.count("O"))

3
3


In [33]:
areas = [1,2,3,4]
areas.append(5)
print(areas)

areas.reverse()
print(areas)

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]


In [34]:
#importing a full package
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [35]:
#importing only specific functions from a package
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [36]:
from math import pi, radians
r = 100000
dist = r*radians(20)
cirm = 2*pi*r

print(dist)
print(cirm)

34906.58503988659
628318.5307179586


<h3> Interesting links</h3>
<ul>
<li>https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex</li>
<li>https://docs.python.org/3.5/library/copy.html</li>
<li>https://www.jeffknupp.com/blog/2014/06/18/improve-your-python-python-classes-and-object-oriented-programming/</li>

In [43]:
#np.arrays allow calculations over list of data, something that doesnt work with standard python lists

height = [11,22,33,44,55,66]
weight = [31,41,51,61,71,81]

import numpy as np
height1 = np.array(height)
weight1 = np.array(weight)
bmi = height1/weight1**2

print(height1)
print(weight1)
print(bmi)

bmi[2]
bmi[bmi<0.012]

[11 22 33 44 55 66]
[31 41 51 61 71 81]
[ 0.01144641  0.01308745  0.01268743  0.01182478  0.01091053  0.01005944]


array([ 0.01144641,  0.01182478,  0.01091053,  0.01005944])

In [39]:
list1 = [1,2,3]
print(list1+list1)

print(np.array(list1)+np.array(list1))

[1, 2, 3, 1, 2, 3]
[2 4 6]
