In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'col1': [2, 4, 6, 3], 'col2': [8, -2, 5, 3]}, 
                    index=pd.MultiIndex.from_tuples([('A', 'B'), ('B', 'A'), ('A', 'C'), ('C', 'A')]))
df.index.names = ['from', 'to']
df

In [ ]:
df2 = df.reset_index()
df2['groups'] = df2[['from','to']].agg(lambda x: tuple(set(x)), axis=1)
df3 = df2.groupby(['groups']).sum().reset_index()
df4 = df3.set_index([df3['groups'].apply(lambda x:x[0]), df3['groups'].apply(lambda x:x[1])]).drop(['groups'], axis=1)
df4.index.names = ['from', 'to']
df4

In [ ]:
df = df.reset_index()
df.index = pd.MultiIndex.from_tuples(df[['from','to']].apply(lambda x: sorted(x), axis=1))
df.groupby(level=[0,1]).sum()

In [ ]:
df = df.reset_index()
df

In [ ]:
df.index = pd.MultiIndex.from_tuples(df[['from','to']].apply(lambda x: sorted(x), axis=1))
df.groupby(level=[0,1]).sum()

In [ ]:
def results(m1, m2):
    compute = np.sum(np.abs(np.array(m1)-np.array(m2)))
    
    if compute==0:
        return 'Fit'
    elif compute==255:
        return 'Hit'
    elif compute==255*len(m1)**2:
        return 'Miss'
    else:
        return 'None'

In [ ]:
m1 = [[255,0,255],
      [0  ,0,  0],
      [255,0,255]]

m2 = [[255,0,255],
      [0  ,0,  0],
      [255,0,255]]

In [ ]:
print('Case 1: ', results(m1, m2))

In [ ]:
m1 = [[255,0,255],
      [0 ,255, 0],
      [255,0,255]]

m2 = [[255,0,255],
      [0  ,0,  0],
      [255,0,255]]

In [ ]:
print('Case 2: ', results(m1, m2))

In [ ]:
m1 = [[0,  255,  0],
      [255,255,255],
      [0  ,255,  0]]

m2 = [[255,0,255],
      [0  ,0,  0],
      [255,0,255]]

In [ ]:
print('Case 3: ', results(m1, m2))

In [ ]:
a = [['Pangarap' ,   'Barbies Cradle',     0.088700 ,   0.566000,    97.091000,   235440,  0],
['I Feel Alive' ,   'Steady Rollin',   0.347000,    0.404000,    135.225000,  373512,  -1],
['Poison',  'Bell Biv DeVoe',  0.489000 ,   0.650000 ,   111.904000 , 262467 , -1]]

In [ ]:
spotify = pd.DataFrame(a, columns=['track_name', 'track_artist','liveness','valence','tempo','duration_me','intervals'])

In [ ]:
def get_random_tracks(interval):
    np.random()

In [ ]:
np.random.choice()

In [ ]:
dd = pd.DataFrame(spotify.groupby(['intervals'])['track_name'].apply(list)).reset_index()
dd['random_track'] = dd['track_name'].apply(np.random.choice, size=(n,))
dd

In [ ]:
df

In [ ]:
df1 = pd.DataFrame(
  {
  'item1_aspect1' : ["a", "b", "c"],
  'item1_aspect2' : [1,2,3],
  'item1_aspect3' : ["[12,34]", "[56,78]", "[99,10]"],
  'item2_aspect1' : ["a", "b", "c"],
  'item2_aspect2' : [1,2,3],
  'item2_aspect3' : ["[12,34]", "[56,78]", "[99,10]"],
  'item3_aspect1' : ["a", "b", "c"],
  'item3_aspect2' : [1,2,3],
  'item3_aspect3' : ["[12,34]", "[56,78]", "[99,10]"]
  })


df2 = pd.DataFrame({
  'aspect_1' : ["a", "b", "c", "a", "b", "c", "a", "b", "c"],
  'aspect_2' : [1,2,3,1,2,3,1,2,3],
  'aspect_3' : ["[12,34]", "[56,78]", "[99,10]", "[12,34]", "[56,78]", "[99,10]", "[12,34]", "[56,78]", "[99,10]"]
})

In [ ]:
n = len(df1.columns)

In [ ]:
lst = list(df1.columns)
n=3
new_cols = ['aspect_1', 'aspect_2', 'aspect_3']
chunks = [lst[i:i + n] for i in range(0, len(lst), n)]
pd.concat([df1[i].set_axis(new_cols, axis=1) for i in chunks], axis=0, ignore_index=True)

In [ ]:
df1[chunks[0]].set_axis(new_cols, axis=1)

In [ ]:
a = 'hi there'

In [ ]:
' '.join([''.join([j[1].lower() if j[0]%2==0 else j[1].upper() for j in enumerate(i)]) for i in a.split()])

In [ ]:
''.join([i[1].lower() if i[0]%2==0 else i[1].upper() for i in enumerate(a)])

In [18]:
df = pd.DataFrame({'Q1': {0: 'test1'}, 'C1': {0: 'a'}, 'I11': {0: 'b'}, 'I12': {0: 'c'}, 'I13': {0: 'd'}, 'Q2': {0: 'test2'}, 'C2': {0: 'e'}, 'I21': {0: 'f'}, 'I22': {0: 'g'}, 'I23': {0: 'h'}, 'Q3': {
       0: 'test3'}, 'C3': {0: 'i'}, 'I31': {0: 'j'}, 'I32': {0: 'k'}, 'I33': {0: 'l'}})

In [ ]:
lst = list(df.columns)
n=5
new_cols = ['Q', 'CA', 'IA1','IA2','IA3']

#break the column list into groups of n = 3 in this case
chunks = [lst[i:i + n] for i in range(0, len(lst), n)]

#concatenate the list of dataframes over axis = 0after renaming columns of each 
pd.concat([df[i].set_axis(new_cols, axis=1) for i in chunks], axis=0, ignore_index=True)

In [ ]:
a = [{'display': 'none'} for i in range(5)]
a[0]['display']='inline'
a

In [ ]:
df = pd.read_excel(
    "https://testme162.s3.amazonaws.com/just_stack.xlsx", header=list(range(5))
)

In [ ]:
expected = pd.read_excel(
    "https://testme162.s3.amazonaws.com/just_stack.xlsx", sheet_name="expected",
)

In [ ]:
expected.head()

In [ ]:
df.head()

In [ ]:
df.columns

In [ ]:
#!pip install -U spacy
#!python -m spacy download en
from nltk import Tree
import spacy
en_nlp = spacy.load('en')

In [ ]:
def tok_format(tok):
    return "_".join([tok.orth_, tok.tag_, tok.dep_])


def to_nltk_tree(node):
    if node.n_lefts + node.n_rights > 0:
        return Tree(tok_format(node), [to_nltk_tree(child) for child in node.children])
    else:
        return tok_format(node)


command = "The chef cooks the soup"
en_doc = en_nlp(u'' + command) 

[to_nltk_tree(sent.root).pretty_print() for sent in en_doc.sents]

In [ ]:
command = "She sells sea shells on the sea shore"
en_doc = en_nlp(u'' + command) 

[to_nltk_tree(sent.root).pretty_print() for sent in en_doc.sents]

In [1]:
from sympy import *

def trapezoid(f, a, b, n):
    h = float(b - a) / n
    result = 0.5 * f.evalf(subs={x: a}) + 0.5 * f.evalf(subs={x: b})
    for i in range(1, n):
        result += f.evalf(subs={x: (a + i * h)})
    result *= h
    return result

if __name__ == "__main__":
    x = Symbol('x')
    fonction = Pow(x,2)
    print(fonction) # x**2
    #print(type(fonction)) # <class 'sympy.core.power.Pow'>

    #print("Expected Result : ", trapezoid(lambda x: x ** 2, 1, 5, 100))

    print("Expected result : ",trapezoid(fonction, 1, 5, 100)) # Won't give me expected result

x**2
Expected result :  41.3344000000000


In [ ]:
schools = [
   {'location':'New York','school-code':[ 'MGOA', 'CityU', 'AKO']}, 
   {'location':'New Jersey','school-code':['GOE']},
   {'location':'California','school-code':['OAS','STO']},
   {'location':'Florida','school-code':['CDY', 'OAK']}
]

In [ ]:
code_input = 'CityU'
l = [i['location'] for i in schools if code_input in i['school-code']][0]
print("Your school zone is",l)

In [6]:
import pandas as pd
df = pd.DataFrame({'index':[1,1,2,2,3,3,4,4], 'Vol':[25,15,20,30,25,10,15,20]}).set_index(['index'])

In [9]:
df.reset_index().set_axis(['index','Vol'], axis=1).groupby(['index'])['Vol'].sum()

index
1    40
2    50
3    35
4    35
Name: Vol, dtype: int64

In [17]:
df.sum(level=0).rolling(2).sum().dropna()

Vol
index      
2      90.0
3      85.0
4      70.0

In [31]:
import numpy as np

In [32]:
data = [['22', '45', '6', '72', '1', '65'], ['2', '65', '67', '23', '98', '1'], ['13', '45', '98', '4', '12', '65']]

In [36]:
dd = np.array(data).astype(int)
dd

array([[22, 45,  6, 72,  1, 65],
       [ 2, 65, 67, 23, 98,  1],
       [13, 45, 98,  4, 12, 65]])

In [44]:
vocab[0]

1

In [74]:
[1] + list(np.sum((dd==vocab[0]).astype(int), axis=0))

[1, 0, 0, 0, 0, 1, 1]

In [118]:
dd = np.array(data).astype(int)   #get the list of lists into a 2d numpy array
vocab = np.unique(dd.flatten())   #get vocab of all unique numbers
df = pd.DataFrame([[i]+list(np.sum((dd==i).astype(int), axis=0)) for i in vocab]) #loop thru vocab and get sum of occurances in each index position
df.columns = ['num', 0, 1, 2, 3, 4, 5]    #rename cols
df['numoccurances'] = df.iloc[:,1:].sum(axis=1)   #create total occurances of the item

#Stack the position counts and rename cols
stats = pd.DataFrame(df.set_index(['num','numoccurances']).\
                     stack()).reset_index().\
                     set_axis(['num', 'numoccurances', 'position', 'numtimesinposition'], axis=1)

stats = stats[stats['numtimesinposition']>0].reset_index(drop=True)

In [119]:
print(stats)

    num  numoccurances  position  numtimesinposition
0     1              2         4                   1
1     1              2         5                   1
2     2              1         0                   1
3     4              1         3                   1
4     6              1         2                   1
5    12              1         4                   1
6    13              1         0                   1
7    22              1         0                   1
8    23              1         3                   1
9    45              2         1                   2
10   65              3         1                   1
11   65              3         5                   2
12   67              1         2                   1
13   72              1         3                   1
14   98              2         2                   1
15   98              2         4                   1


In [115]:
print(stats)

    num  numoccurances  position  numtimesinposition
4     1              2         4                   1
5     1              2         5                   1
6     2              1         0                   1
15    4              1         3                   1
20    6              1         2                   1
28   12              1         4                   1
30   13              1         0                   1
36   22              1         0                   1
45   23              1         3                   1
49   45              2         1                   2
55   65              3         1                   1
59   65              3         5                   2
62   67              1         2                   1
69   72              1         3                   1
74   98              2         2                   1
76   98              2         4                   1


In [196]:
df = pd.DataFrame({
'Color': ['r','r','r','b'],
'Marker': ['^','*','^','*']
})


from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

df['combined'] = df.apply(lambda x: ''.join(x), axis=1)
df['combined'] = lb.fit_transform(df['combined'])
print(df)

  Color Marker  combined
0     r      ^         2
1     r      *         1
2     r      ^         2
3     b      *         0


In [197]:
list(enumerate(lb.classes_))

[(0, 'b*'), (1, 'r*'), (2, 'r^')]

In [203]:
[tuple(i) for i in lb.inverse_transform([0, 2, 1])]

[('b', '*'), ('r', '^'), ('r', '*')]

In [211]:
s =  'fell down the stairs and ate an apple so no doctor #quarantine'
allwords = s.split(' ')
allwords

['fell',
 'down',
 'the',
 'stairs',
 'and',
 'ate',
 'an',
 'apple',
 'so',
 'no',
 'doctor',
 '#quarantine']

In [210]:
hastags = [i for i in allwords if i[:1]=='#']
hastags

['#quarantine']

In [213]:
otherwords = [i for i in allwords if i not in hastags]
otherwords

['fell',
 'down',
 'the',
 'stairs',
 'and',
 'ate',
 'an',
 'apple',
 'so',
 'no',
 'doctor']

In [223]:
tags = ["corona", "quarantine", "covid19"]
print([i for i in s.split(' ') if i.strip('#') not in tags])

['fell', 'down', 'the', 'stairs', 'and', 'ate', 'an', 'apple', 'so', 'no', 'doctor']


['fell',
 'down',
 'the',
 'stairs',
 'and',
 'ate',
 'an',
 'apple',
 'so',
 'no',
 'doctor']

In [217]:
'abcd'.strip('a')

'bcd'

In [225]:
tags = ["corona", "quarantine", "covid19"]
print([i for i in s.split(' ') if i.strip('#') not in tags and i not in tags])

['fell', 'down', 'the', 'stairs', 'and', 'ate', 'an', 'apple', 'so', 'no', 'doctor']


In [234]:
word = 'sender'
others = ['bnder', 'snder', 'sender', 'hello']

process.extractBests(word, others)

[('sender', 100), ('snder', 91), ('bnder', 73), ('hello', 18)]

In [241]:
[(i, fuzz.ratio(word, i)) for i in others]

[('bnder', 73), ('snder', 91), ('sender', 100), ('hello', 18)]

In [318]:
df = pd.DataFrame(['hi there i am a sender', 
                   'I dont wanna be a bnder', 
                   'can i be the snder?', 
                   'i think i am a nerd',
                   'i next to selx a bit'], columns=['text'])

In [319]:
def get_match(s,w,t):
    ss = process.extractBests(w,s.split())
    return any([i[1]>t for i in ss])

In [ ]:
df['match'] = df['text'].apply(get_match, w='sender', t=70)
print(df)

In [320]:
options = ['sender','slx']
for i in options:
    df[i] = df['text'].apply(get_match, w=i, t=70)

In [321]:
df

text  sender    slx
0   hi there i am a sender    True  False
1  I dont wanna be a bnder    True  False
2      can i be the snder?    True  False
3      i think i am a nerd   False  False
4     i next to selx a bit   False   True

In [280]:
print(df[df['match']==True][['text']])

text
0   hi there i am a sender
1  I dont wanna be a bnder
2      can i be the snder?

In [281]:
import pandas as pd 
df=pd.DataFrame({'rating':[5.0,4.5,3.0,2.5,4.0,4.5,5.0,3.0],
             'productname':['s','v','r','n','k','a','q','w'],
             'category':['mobile','mobile','mobile','mobile','laptop','laptop','laptop','laptop']
         })

In [282]:
df.nlargest

rating productname category
0     5.0           s   mobile
1     4.5           v   mobile
2     3.0           r   mobile
3     2.5           n   mobile
4     4.0           k   laptop
5     4.5           a   laptop
6     5.0           q   laptop
7     3.0           w   laptop

In [299]:
print(df.groupby(['category']).apply(lambda x:x.nlargest(3, 'rating')))

            rating productname category
category                               
laptop   6     5.0           q   laptop
         5     4.5           a   laptop
         4     4.0           k   laptop
mobile   0     5.0           s   mobile
         1     4.5           v   mobile
         2     3.0           r   mobile


In [308]:
lst_a = ['zero one two', 'three four five six', 'one two', 'five four nine twelve ten', 'five fifty eleven four'] 
lst_b = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'one', 'two', 'five', 'four', 'nine', 'twelve', 'ten']

common_tokens = [set(i.split()).intersection(set(lst_b)) for i in lst_a]
new_lst = [' '.join(i) for i in common_tokens]
new_lst

In [311]:
print(new_lst)

['one two zero', 'three four six five', 'one two', 'nine four ten twelve five', 'four five']


In [350]:
d = {"z": 1.6, "aaaaaaaaaaaaa": 0, "w": 6, "v": 4}
dict(sorted(d.items(), key=lambda x:x[1], reverse=True))

{'w': 6, 'v': 4, 'z': 1.6, 'aaaaaaaaaaaaa': 0}

In [352]:
import itertools

In [355]:
#randomList = [[1,2,3],[4,5,6],[7,8,9]]
randomList = [['A','B','C'],['D','E','F'],['G','H','I']]
for el in itertools.product(*randomList):
        print(randomList)

[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
[['A', 'B', 

In [373]:
vocab = np.unique(a.values)

In [423]:
vocab

array(['(-1.774, 1.145]', '(-3.21, 0.533]', '(0.0166, 2.007]',
       '(2.0, 3.997]', '(2.007, 3.993]'], dtype=object)

In [455]:
from sklearn.feature_extraction.text import CountVectorizer

cnt = CountVectorizer(vocabulary=vocab)

In [ ]:
l

In [523]:
df = pd.DataFrame([['(-1.774, 1.145]','(-3.21, 0.533]','(0.0166, 2.007]','(2.0, 3.997]'],
                ['(-1.774, 1.145]','(-3.21, 0.533]','(2.007, 3.993]','(2.0, 3.997]']])
df = df.astype(str)
print(df)

                 0               1                2             3
0  (-1.774, 1.145]  (-3.21, 0.533]  (0.0166, 2.007]  (2.0, 3.997]
1  (-1.774, 1.145]  (-3.21, 0.533]   (2.007, 3.993]  (2.0, 3.997]


In [520]:
from sklearn.preprocessing import OneHotEncoder

l = OneHotEncoder()
data = l.fit_transform(df.values)
co_occurance = np.dot(data.T, data)

vocab = [i[3:] for i in l.get_feature_names()]
ddf = pd.DataFrame(co_occurance.todense(), columns=vocab, index=vocab)

In [522]:
print(ddf)

                 (-1.774, 1.145]  (-3.21, 0.533]  (0.0166, 2.007]  \
(-1.774, 1.145]              2.0             2.0              1.0   
(-3.21, 0.533]               2.0             2.0              1.0   
(0.0166, 2.007]              1.0             1.0              1.0   
(2.007, 3.993]               1.0             1.0              0.0   
(2.0, 3.997]                 2.0             2.0              1.0   

                 (2.007, 3.993]  (2.0, 3.997]  
(-1.774, 1.145]             1.0           2.0  
(-3.21, 0.533]              1.0           2.0  
(0.0166, 2.007]             0.0           1.0  
(2.007, 3.993]              1.0           1.0  
(2.0, 3.997]                1.0           2.0  


In [448]:
np.eye(len(vocab))[]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [454]:
vocab

array(['(-1.774, 1.145]', '(-3.21, 0.533]', '(0.0166, 2.007]',
       '(2.0, 3.997]', '(2.007, 3.993]'], dtype=object)

In [453]:
[[j for j in i] for i in a.values]

[['(-1.774, 1.145]', '(-3.21, 0.533]', '(0.0166, 2.007]', '(2.0, 3.997]'],
 ['(-1.774, 1.145]', '(-3.21, 0.533]', '(2.007, 3.993]', '(2.0, 3.997]']]

In [443]:
l.classes_

array(['(-1.774, 1.145]', '(-3.21, 0.533]', '(0.0166, 2.007]',
       '(2.0, 3.997]', '(2.007, 3.993]'], dtype='<U15')

In [ ]:
a.apply(i for i in)

In [427]:
sent = [' '.join(i) for i in a.apply(list, axis=1)]
sent

['(-1.774, 1.145] (-3.21, 0.533] (0.0166, 2.007] (2.0, 3.997]',
 '(-1.774, 1.145] (-3.21, 0.533] (2.007, 3.993] (2.0, 3.997]']

In [435]:
cnt.transform([['(-1.774, 1.145]','(-3.21, 0.533]','(0.0166, 2.007]','(2.0, 3.997]']]).todense()

AttributeError: 'list' object has no attribute 'lower'

In [428]:
cnt.transform(sent).todense()

matrix([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [429]:
cnt.vocabulary_

{'(-1.774, 1.145]': 0,
 '(-3.21, 0.533]': 1,
 '(0.0166, 2.007]': 2,
 '(2.0, 3.997]': 3,
 '(2.007, 3.993]': 4}

In [382]:
encoded_df = lb.fit_transform(a.values.ravel()).reshape(a.shape)

In [383]:
encoded_df

array([[0, 1, 2, 3],
       [0, 1, 4, 3]])

In [524]:
group1 = [['a','b','c'], ['1','2','3'], ['x','y','z','w'],['10','20','30','40']]
group2 = [['a','b','x','z'], ['1','2','3','4','5'], ['x','y','z','q','p'],['10','50','60','70']]
group3 = [['a','b','c','x','1'], ['1','2','3','4','6'], ['y','z','w','5'],['10','20','60','70']]

def match(grp1, grp2):
    for arr1 in grp1:
        for arr2 in grp2:
            overlap = len(arr1) + len(arr2) - len(set(arr1+arr2))
            if overlap > 0:
                print(overlap, overlap/len(arr1), overlap/len(arr2), arr1, arr2)

In [525]:
match(group1, group2)

2 0.6666666666666666 0.5 ['a', 'b', 'c'] ['a', 'b', 'x', 'z']
3 1.0 0.6 ['1', '2', '3'] ['1', '2', '3', '4', '5']
2 0.5 0.5 ['x', 'y', 'z', 'w'] ['a', 'b', 'x', 'z']
3 0.75 0.6 ['x', 'y', 'z', 'w'] ['x', 'y', 'z', 'q', 'p']
1 0.25 0.25 ['10', '20', '30', '40'] ['10', '50', '60', '70']


In [527]:
from fuzzywuzzy import fuzz, process

In [543]:
fuzz.partial_ratio(group1[0], group2[0])

87

In [548]:
ll = list(itertools.product(group1, group2))

In [551]:
from distance import levenshtein

In [ ]:
def common(l1, l2):
    inter = l1.
    return 

In [552]:
levenshtein(group1[0], group2[0])

2

In [554]:
list1=[2, 1, 0]
list2=[[1820, 6700, 22260, 28820, 35420],[2140, 3640, 3660, 4180, 5400, 13020],[5920, 13980, 18820, 21280]]

In [558]:
[list1[i] for i in range(len(list1))]

[2, 1, 0]

In [569]:
[*map(list.__getitem__, list2, list1)]

[22260, 3640, 5920]

In [565]:
list.__getitem__()

<method '__getitem__' of 'list' objects>

In [566]:
map()

map

In [571]:
inp = [3, 4, 4, 4, 5, 6, 6, 5, 4, 4]

In [575]:
items = np.unique(inp, return_counts=True)

In [585]:
[inp[i:i+2] for i in range(len(inp))]

[[3, 4], [4, 4], [4, 4], [4, 5], [5, 6], [6, 6], [6, 5], [5, 4], [4, 4], [4]]

In [601]:
l = [i for i in zip(inp, inp[1:]) if i[0]==i[1]]
out = [k[0] for k, g in itertools.groupby(l)]
#l2 = [i for i in l]

In [607]:
[i for i in l]

[(4, 4), (4, 4), (6, 6), (4, 4)]

[4, 6, 4]

In [576]:
[i for i in zip(items[0], items[1])]

[(3, 1), (4, 5), (5, 2), (6, 2)]

In [617]:
[(k,len(list(g))) for k,g in itertools.groupby(l)]

[((4, 4), 2), ((6, 6), 1), ((4, 4), 1)]

In [621]:
import tensorflow as tf

In [624]:
inputs = tf.keras.Input(shape=(4,))
x = tf.keras.layers.Dense(3)(inputs)
x = tf.keras.layers.Activation(tf.nn.sigmoid)(x)
x = tf.keras.layers.Dense(2)(x)
outputs = tf.keras.layers.Activation(tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs, name="simple_binary_iris")
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=["accuracy"] )
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 15        
_________________________________________________________________
activation_2 (Activation)    (None, 3)                 0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 8         
_________________________________________________________________
activation_3 (Activation)    (None, 2)                 0         
Total params: 23
Trainable params: 23
Non-trainable params: 0
_________________________________________________________________


In [626]:
inputs

<tf.Tensor 'input_4:0' shape=(?, 4) dtype=float32>

In [657]:
a = [1,2,2,3,4,4,0]

In [641]:
arr.shape

(1, 4, 5)

In [672]:
arr = np.array([[[ 0,  0,  0,  3,  0],
                [ 0,  0,  2,  3,  2],
                [ 0,  0,  0,  0,  0],
                [ 2,  1,  0,  0, 0]]])

In [673]:
np.apply_along_axis(np.unique, axis=2, arr=arr)

ValueError: could not broadcast input array from shape (3) into shape (2)

In [706]:
a = np.array([ 0,  0,  2,  3,  2])

In [713]:
a[np.argmax(np.sum(np.eye(5)[a][:,1:], axis=0))+1]

2

In [726]:
arr

array([[[0, 0, 0, 3, 0],
        [0, 0, 2, 3, 2],
        [0, 0, 0, 0, 0],
        [2, 1, 0, 0, 0]]])

In [808]:
count_max_pos

array([3, 2, 1, 1])

In [801]:
#Gets the positions for the highest frequency numbers in axis=2
count_max_pos = np.argmax(np.sum(np.eye(5)[arr][:,:,:,1:], axis=2), axis=2)[0]+1

#gets the max values in based on the indices
k = enumerate(count_max_pos)
result = [arr[0][i] for i in k]

print(result)

[3, 2, 0, 1]


In [802]:
a

array([0, 0, 2, 3, 2])