In [2]:
a = 'Python'

il = (a[:-1],'abc')
il

('Pytho', 'abc')

SyntaxError: can't use starred expression here (<ipython-input-3-5dfd481a4e76>, line 1)

In [14]:
z = 1
x = []
num = [i for i in range(0,20)]

for i in num:
    x.append(z)
    z*=i
    
    
x

SyntaxError: invalid syntax (<ipython-input-14-83138818d906>, line 6)

In [12]:
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [17]:
from pyknow import Fact

In [18]:
f = Fact(a=1, b=2)

In [21]:
f['a']

1

In [23]:
f = Fact('x','y',a=1,b=2)

In [24]:
f[0]

'x'

In [25]:
f[1]

'y'

In [29]:
f['b']

2

In [30]:
class MyFact(Fact):
    pass

In [32]:
MyFact(f)

MyFact(<frozendict {0: 'x', 1: 'y', 'a': 1, 'b': 2}>)

In [38]:
import numpy as np

In [40]:
sum([1,2,3,4,5])

15

In [47]:
def mydecorator(f):
    def wrapper():
        print("inside decorator before func")
        f()
        print("inside decorator after func")
    return wrapper

@mydecorator
def printname():
    print('Akshay')

In [48]:
printname()

inside decorator before func
Akshay
inside decorator after func


In [ ]:
@Rule(MyFact())  # This is the LHS
def match_with_every_myfact():
    """This rule will match with every instance of `MyFact`."""
    # This is the RHS
    pass

In [367]:
statements = [['i like this phone','phone not to shabby'],['i hate this device','not really usable']]

In [368]:
from sklearn.feature_extraction.text import CountVectorizer

cnt = CountVectorizer()

In [371]:
cnt.fit([i for sublist in statements for i in sublist])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [372]:
def make_readable(f):
    def wrapper(*args,**kwargs):
        print("Readable format :")
        cols = list(dict(sorted(cnt.vocabulary_.items(), key=lambda x:x[1])).keys())
        df = pd.DataFrame(columns=cols)
        x = f(*args,**kwargs)
        for i in range(x.shape[0]):
            df.loc[i] = x[i]
        return df
    return wrapper

In [373]:
def avg_embeddings(f):
    def wrapper(*args, **kwargs):
        x = f(*args,**kwargs)
        x1 = np.mean(x, axis=0).reshape(1,10)
        return x1
    return wrapper

In [374]:
@make_readable
@avg_embeddings
def get_sentence_embeddings(comments):
    return cnt.transform(comments).toarray()

In [376]:
[get_sentence_embeddings(i) for i in statements]

Readable format :
Readable format :


[   device  hate  like  not  phone  really  shabby  this   to  usable
 0     0.0   0.0   0.5  0.5    1.0     0.0     0.5   0.5  0.5     0.0,
    device  hate  like  not  phone  really  shabby  this   to  usable
 0     0.5   0.5   0.0  0.5    0.0     0.5     0.0   0.5  0.0     0.5]

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'col1':[1,2,3], 'col2':[1,0,0], 'col3':[1,0,0]})

In [4]:
df

col1  col2  col3
0     1     1     1
1     2     0     0
2     3     0     0

value_counts
0             4
1             3
2             1
3             1

In [36]:
img = np.random.random((4,4,3))
img

array([[[0.04612523, 0.7076162 , 0.0077522 ],
        [0.95218088, 0.48891562, 0.04766992],
        [0.28984489, 0.49045226, 0.66813344],
        [0.83308677, 0.15540987, 0.37064375]],

       [[0.99815238, 0.76337319, 0.77432304],
        [0.59248832, 0.6646004 , 0.40680268],
        [0.47610131, 0.79314052, 0.23590698],
        [0.26205002, 0.14437162, 0.88849931]],

       [[0.37773638, 0.73637243, 0.18386754],
        [0.59428725, 0.90606256, 0.34678647],
        [0.27745484, 0.32770843, 0.75953475],
        [0.06070188, 0.63356902, 0.80353941]],

       [[0.94564578, 0.75601306, 0.83159874],
        [0.80336703, 0.74640845, 0.91632327],
        [0.9427936 , 0.14277121, 0.37661809],
        [0.76609366, 0.98227002, 0.65687497]]])

In [38]:
img.reshape((4*4,3))

array([[0.04612523, 0.7076162 , 0.0077522 ],
       [0.95218088, 0.48891562, 0.04766992],
       [0.28984489, 0.49045226, 0.66813344],
       [0.83308677, 0.15540987, 0.37064375],
       [0.99815238, 0.76337319, 0.77432304],
       [0.59248832, 0.6646004 , 0.40680268],
       [0.47610131, 0.79314052, 0.23590698],
       [0.26205002, 0.14437162, 0.88849931],
       [0.37773638, 0.73637243, 0.18386754],
       [0.59428725, 0.90606256, 0.34678647],
       [0.27745484, 0.32770843, 0.75953475],
       [0.06070188, 0.63356902, 0.80353941],
       [0.94564578, 0.75601306, 0.83159874],
       [0.80336703, 0.74640845, 0.91632327],
       [0.9427936 , 0.14277121, 0.37661809],
       [0.76609366, 0.98227002, 0.65687497]])

In [29]:
import matplotlib.pyplot as plt

In [31]:
img = plt.imread('/Users/akshay/Desktop/images.png')

In [32]:
img.shape

(225, 225, 3)

In [39]:
a = {"config":"4", "location":"C:\\xyz", "Group":"amcat"}
b = {"config":"4", "location":"C:\\xyz", "Group":"amcat"}
c = {"config":"5", "location":"C:\\mno", "Group":"alien"}
d = {"config":"5", "location":"C:\\mno", "Group":"alien"}

In [42]:
list_dicts = [a,b,c,d]

In [43]:
list_dicts

[{'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'},
 {'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'},
 {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'},
 {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'}]

In [59]:
values = np.array([list(i.values()) for i in list_dicts])

In [71]:
uniques = np.unique(values, axis=0)

In [87]:
idx = [[j for j in range(len(values)) if all(values[j]==i)] for i in uniques]
idx

[[0, 1], [2, 3]]

In [88]:
dictXml = {
'a.xml': {"config":"4", "location":"C:\\xyz", "Group":"amcat"},
'c.xml': {"config":"5", "location":"C:\\mno", "Group":"alien"},
'b.xml': {"config":"4", "location":"C:\\xyz", "Group":"amcat"},
'd.xml': {"config":"5", "location":"C:\\mno", "Group":"alien"},
}

In [117]:
new_df = {k:list(v.values()) for k,v in dictXml.items()}
new_df

{'a.xml': ['4', 'C:\\xyz', 'amcat'],
 'c.xml': ['5', 'C:\\mno', 'alien'],
 'b.xml': ['4', 'C:\\xyz', 'amcat'],
 'd.xml': ['5', 'C:\\mno', 'alien']}

In [124]:
dictXml

{'a.xml': {'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'},
 'c.xml': {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'},
 'b.xml': {'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'},
 'd.xml': {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'}}

In [129]:
[(k,v) for k,v in dictXml.items()]

[('a.xml', {'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'}),
 ('c.xml', {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'}),
 ('b.xml', {'config': '4', 'location': 'C:\\xyz', 'Group': 'amcat'}),
 ('d.xml', {'config': '5', 'location': 'C:\\mno', 'Group': 'alien'})]

In [139]:
grid = np.array([ 
[0,2,1,0],
[0,1,0,-1]])

In [140]:
grid

array([[ 0,  2,  1,  0],
       [ 0,  1,  0, -1]])

In [141]:
grid==2

array([[False,  True, False, False],
       [False, False, False, False]])

In [145]:
np.argwhere(grid==2)

array([[0, 1]])

In [153]:
np.argwhere(grid==0)

array([[0, 0],
       [0, 3],
       [1, 0],
       [1, 2]])