In [2]:
import random

types = ["places", "names"]

places = ["The Upper Room", "Jerusalem", "Church", "Rome"]
names = ["Jesus", "Desciples", "Paul"]


def get_random_type():
    return random.choice(types)

def get_response(chosentype):
    return random.choice(eval(chosentype))

randtype = get_random_type()
print(randtype)
print(get_response(randtype))

names
Desciples


In [3]:
example_list = [
    ['a','b','c'],
    ['f','g','h'],
    ['i','j','k'],
]

s = '\n'.join([str(tuple(i)) for i in example_list])
print(s)

('a', 'b', 'c')
('f', 'g', 'h')
('i', 'j', 'k')


In [4]:
a = [[['7', '3', 'SELL', 'chair_1', '30.00'], ['17', '4', 'BID', 'chair_1', '34.00']]]
b = [[['14', '5', 'SELL', 'toaster_1', '14.50', '30']]]
c = [[['10', '1', 'SELL', 'radio_1', '10.00', '30'], ['13', '5', 'BID', 'radio_1', '12.50'], ['16', '6', 'BID', 'radio_1', '12.50']]]
d = [[['12', '4', 'SELL', 'TV_1', '200.00', '35'], ['15', '8', 'BID', 'TV_1', '250.00'], ['18', '1', 'BID', 'TV_1', '150.00'], ['19', '3', 'BID', 'TV_1', '200.00'], ['21', '3', 'BID', 'TV_1', '300.00']]]
e = [[['11', '3', 'SELL', 'transistor_1', '15.00', '30'], ['20', '7', 'BID', 'transistor_1', '20.00']]]

def get_min_auc(auc):
    d = [j for i in auc[0][1:] for j in i if len(j.split('.'))>1]
    try: return min(d)
    except: return 0

print(get_min_auc(a))
print(get_min_auc(b))
print(get_min_auc(c))
print(get_min_auc(d))
print(get_min_auc(e))

34.00
0
12.50
150.00
20.00


In [6]:
a = "abijkabccbakfgba"

def isp(s):
    return s == s[::-1]

res = (a[i: j] for i in range(len(a)) for j in range(i + 1, len(a) + 1))
palindromes = sorted([i for i in res if isp(i) and len(i)>1], key = lambda x: len(x), reverse=True)[0]
palindromes

'kabccbak'

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.DataFrame({
    'Mountain Range': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D'], 
    'Peak': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's'], 
    'Height above sea level': [2340, 3050, 4220, 2675, 2980, 3300, 3405, 3410, 2970, 2840, 2780, 3140, 3210, 2885, 3000, 3110, 2640, 2635]
    })

In [36]:
df[df['Mountain Range']=='A'].nlargest(3, 'Height above sea level')

Mountain Range Peak  Height above sea level
2              A    c                    4220
1              A    b                    3050
4              A    e                    2980

In [52]:
g = df.groupby('Mountain Range')['Height above sea level'].apply(lambda x: np.sum(x.nlargest(3))).reset_index()
print(g)

g.nlargest(1, 'Height above sea level')['Mountain Range'][0]

  Mountain Range  Height above sea level
0              A                   10250
1              B                   10115
2              C                    9235
3              D                    8750


In [56]:
g.nlargest(1, 'Height above sea level')['Mountain Range'][0]

'A'

In [59]:
data = pd.DataFrame({'Name':['Joe','Joe','Jackson','Jackson'],'Computer':['MAC','HP','MAC','HP'],'Data':[10,5,20,15]})

In [72]:
pd.pivot(data, index='Name',columns='Computer', values='Data')

Computer  HP  MAC
Name             
Jackson   15   20
Joe        5   10

In [76]:
print(data.set_index(['Name','Computer']).unstack(-1))

         Data    
Computer   HP MAC
Name             
Jackson    15  20
Joe         5  10


In [129]:
Change = np.random.randint(-2,4,size=(2,5))
pct_change = np.random.randint(1,3,size=(2,5))
Change_after_calculation = np.zeros_like(pct_change)

for p in range(5):
    for n in range(2):
        if Change[n,p] < 0:
            Change_after_calculation[n,p] = (1+pct_change[n,p]) *  Change[n,p]
        else:
            Change_after_calculation[n,p] = Change[n,p]

array([[ 0, -1,  0,  3,  3],
       [ 2, -1,  3,  2, -2]])

In [130]:

\pct_change

array([[2, 1, 2, 1, 1],
       [1, 2, 2, 1, 1]])

In [131]:

Change_after_calculation

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [137]:
for p in range(5):
    for n in range(2):
        if Change[n,p] < 0:
            Change_after_calculation[n,p] = (1+pct_change[n,p]) *  Change[n,p]
        else:
            Change_after_calculation[n,p] = Change[n,p]

In [138]:
Change_after_calculation

array([[ 0, -2,  0,  3,  3],
       [ 2, -3,  3,  2, -4]])

In [139]:
(Change>=0)*Change +(Change<0)*(pct_change+1)*Change

array([[ 0, -2,  0,  3,  3],
       [ 2, -3,  3,  2, -4]])

In [140]:
colors  = ['red', 'blue', 'yellow' , 'purple']
things = ['apple', 'pickle', 'tomato' , 'rainbow', 'book']

corpus = ['i ate a red apple.', 'There are so many colors in the rainbow.', 'the monster was purple and green.', 'the pickle is very green', 'the kid read the book the little red riding hood', 'in the book the wizard of oz there was a yellow brick road.', 'tom has a green thumb and likes working in a garden.' ]

In [236]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
out = cv.fit_transform(corpus).toarray() #apply countvectorizer

combined = colors+things  #combine all your topics

c = [(k,v) for k,v in cv.vocabulary_.items() if k in combined] #get indexes for all the items from all topics

cdf = pd.DataFrame(out[:,[i[1] for i in c]], columns=[i[0] for i in c]).T  #Filter cv dataframe for all items

print(cdf)

         0  1  2  3  4  5  6
red      1  0  0  0  1  0  0
apple    1  0  0  0  0  0  0
rainbow  0  1  0  0  0  0  0
purple   0  0  1  0  0  0  0
pickle   0  0  0  1  0  0  0
book     0  0  0  0  1  1  0
yellow   0  0  0  0  0  1  0


In [298]:
def get_similary_table(topic=None):
    if topic==None:
        df = cdf
    else:
        df = cdf.loc[cdf.index.isin(topic)]  #filter by topic
    cnd = df.values
    similarity = cnd.T@cnd #Take dot product to get similarty matrix
    dd = pd.DataFrame(similarity, index=corpus, columns=corpus) #convert to a dataframe
    return dd

In [288]:
def get_similar_review(s, topic):
    df = cdf.loc[cdf.index.isin(topic)] #filter by topic
    cnd = df.values
    similarity = cnd.T@cnd #Take dot product to get similarty matrix
    np.fill_diagonal(similarity,0) #set diagonal elements to 0, to avoid same sentence being returned as output
    dd = pd.DataFrame(similarity, index=corpus, columns=corpus) #convert to a dataframe
    return dd.loc[s].idxmax(axis=0) #filter by sentence and get column name with max value

In [285]:
s = 'i ate a red apple.'
get_similar(s, colors)

'the kid read the book the little red riding hood'

In [286]:
s = 'the kid read the book the little red riding hood'
get_similar(s, things)

'in the book the wizard of oz there was a yellow brick road.'

In [299]:
get_similary_table()

i ate a red apple.  \
i ate a red apple.                                                   2   
There are so many colors in the rainbow.                             0   
the monster was purple and green.                                    0   
the pickle is very green                                             0   
the kid read the book the little red riding hood                     1   
in the book the wizard of oz there was a yellow...                   0   
tom has a green thumb and likes working in a ga...                   0   

                                                    There are so many colors in the rainbow.  \
i ate a red apple.                                                                         0   
There are so many colors in the rainbow.                                                   1   
the monster was purple and green.                                                          0   
the pickle is very green                                                                   0   
the kid read the book the little red riding hood                                           0   
in the book the wizard of oz there was a yellow...                                         0   
tom has a green thumb and likes working in a ga...                                         0   

                                                    the monster was purple and green.  \
i ate a red apple.                                                                  0   
There are so many colors in the rainbow.                                            0   
the monster was purple and green.                                                   1   
the pickle is very green                                                            0   
the kid read the book the little red riding hood                                    0   
in the book the wizard of oz there was a yellow...                                  0   
tom has a green thumb and likes working in a ga...                                  0   

                                                    the pickle is very green  \
i ate a red apple.                                                         0   
There are so many colors in the rainbow.                                   0   
the monster was purple and green.                                          0   
the pickle is very green                                                   1   
the kid read the book the little red riding hood                           0   
in the book the wizard of oz there was a yellow...                         0   
tom has a green thumb and likes working in a ga...                         0   

                                                    the kid read the book the little red riding hood  \
i ate a red apple.                                                                                 1   
There are so many colors in the rainbow.                                                           0   
the monster was purple and green.                                                                  0   
the pickle is very green                                                                           0   
the kid read the book the little red riding hood                                                   2   
in the book the wizard of oz there was a yellow...                                                 1   
tom has a green thumb and likes working in a ga...                                                 0   

                                                    in the book the wizard of oz there was a yellow brick road.  \
i ate a red apple.                                                                                  0             
There are so many colors in the rainbow.                                                            0             
the monster was purple and green.                                                                   0             
the pickle is very green                   

In [331]:
a = pd.DataFrame([[1,2,2],[3,4,5]], columns=['A','B','C'])
print(a)

   A  B  C
0  1  2  2
1  3  4  5


In [337]:
grp = a.groupby([True]*len(a))
grp