In [2]:
import random

types = ["places", "names"]

places = ["The Upper Room", "Jerusalem", "Church", "Rome"]
names = ["Jesus", "Desciples", "Paul"]


def get_random_type():
    return random.choice(types)

def get_response(chosentype):
    return random.choice(eval(chosentype))

randtype = get_random_type()
print(randtype)
print(get_response(randtype))

names
Desciples


In [3]:
example_list = [
    ['a','b','c'],
    ['f','g','h'],
    ['i','j','k'],
]

s = '\n'.join([str(tuple(i)) for i in example_list])
print(s)

('a', 'b', 'c')
('f', 'g', 'h')
('i', 'j', 'k')


In [4]:
a = [[['7', '3', 'SELL', 'chair_1', '30.00'], ['17', '4', 'BID', 'chair_1', '34.00']]]
b = [[['14', '5', 'SELL', 'toaster_1', '14.50', '30']]]
c = [[['10', '1', 'SELL', 'radio_1', '10.00', '30'], ['13', '5', 'BID', 'radio_1', '12.50'], ['16', '6', 'BID', 'radio_1', '12.50']]]
d = [[['12', '4', 'SELL', 'TV_1', '200.00', '35'], ['15', '8', 'BID', 'TV_1', '250.00'], ['18', '1', 'BID', 'TV_1', '150.00'], ['19', '3', 'BID', 'TV_1', '200.00'], ['21', '3', 'BID', 'TV_1', '300.00']]]
e = [[['11', '3', 'SELL', 'transistor_1', '15.00', '30'], ['20', '7', 'BID', 'transistor_1', '20.00']]]

def get_min_auc(auc):
    d = [j for i in auc[0][1:] for j in i if len(j.split('.'))>1]
    try: return min(d)
    except: return 0

print(get_min_auc(a))
print(get_min_auc(b))
print(get_min_auc(c))
print(get_min_auc(d))
print(get_min_auc(e))

34.00
0
12.50
150.00
20.00


In [6]:
a = "abijkabccbakfgba"

def isp(s):
    return s == s[::-1]

res = (a[i: j] for i in range(len(a)) for j in range(i + 1, len(a) + 1))
palindromes = sorted([i for i in res if isp(i) and len(i)>1], key = lambda x: len(x), reverse=True)[0]
palindromes

'kabccbak'

In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.DataFrame({
    'Mountain Range': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D'], 
    'Peak': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's'], 
    'Height above sea level': [2340, 3050, 4220, 2675, 2980, 3300, 3405, 3410, 2970, 2840, 2780, 3140, 3210, 2885, 3000, 3110, 2640, 2635]
    })

In [36]:
df[df['Mountain Range']=='A'].nlargest(3, 'Height above sea level')

Mountain Range Peak  Height above sea level
2              A    c                    4220
1              A    b                    3050
4              A    e                    2980

In [52]:
g = df.groupby('Mountain Range')['Height above sea level'].apply(lambda x: np.sum(x.nlargest(3))).reset_index()
print(g)

g.nlargest(1, 'Height above sea level')['Mountain Range'][0]

  Mountain Range  Height above sea level
0              A                   10250
1              B                   10115
2              C                    9235
3              D                    8750


In [56]:
g.nlargest(1, 'Height above sea level')['Mountain Range'][0]

'A'

In [59]:
data = pd.DataFrame({'Name':['Joe','Joe','Jackson','Jackson'],'Computer':['MAC','HP','MAC','HP'],'Data':[10,5,20,15]})

In [72]:
pd.pivot(data, index='Name',columns='Computer', values='Data')

Computer  HP  MAC
Name             
Jackson   15   20
Joe        5   10

In [76]:
print(data.set_index(['Name','Computer']).unstack(-1))

         Data    
Computer   HP MAC
Name             
Jackson    15  20
Joe         5  10


In [129]:
Change = np.random.randint(-2,4,size=(2,5))
pct_change = np.random.randint(1,3,size=(2,5))
Change_after_calculation = np.zeros_like(pct_change)

for p in range(5):
    for n in range(2):
        if Change[n,p] < 0:
            Change_after_calculation[n,p] = (1+pct_change[n,p]) *  Change[n,p]
        else:
            Change_after_calculation[n,p] = Change[n,p]

array([[ 0, -1,  0,  3,  3],
       [ 2, -1,  3,  2, -2]])

In [130]:

\pct_change

array([[2, 1, 2, 1, 1],
       [1, 2, 2, 1, 1]])

In [131]:

Change_after_calculation

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [137]:
for p in range(5):
    for n in range(2):
        if Change[n,p] < 0:
            Change_after_calculation[n,p] = (1+pct_change[n,p]) *  Change[n,p]
        else:
            Change_after_calculation[n,p] = Change[n,p]

In [138]:
Change_after_calculation

array([[ 0, -2,  0,  3,  3],
       [ 2, -3,  3,  2, -4]])

In [139]:
(Change>=0)*Change +(Change<0)*(pct_change+1)*Change

array([[ 0, -2,  0,  3,  3],
       [ 2, -3,  3,  2, -4]])

In [140]:
colors  = ['red', 'blue', 'yellow' , 'purple']
things = ['apple', 'pickle', 'tomato' , 'rainbow', 'book']

corpus = ['i ate a red apple.', 'There are so many colors in the rainbow.', 'the monster was purple and green.', 'the pickle is very green', 'the kid read the book the little red riding hood', 'in the book the wizard of oz there was a yellow brick road.', 'tom has a green thumb and likes working in a garden.' ]

In [236]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
out = cv.fit_transform(corpus).toarray() #apply countvectorizer

combined = colors+things  #combine all your topics

c = [(k,v) for k,v in cv.vocabulary_.items() if k in combined] #get indexes for all the items from all topics

cdf = pd.DataFrame(out[:,[i[1] for i in c]], columns=[i[0] for i in c]).T  #Filter cv dataframe for all items

print(cdf)

         0  1  2  3  4  5  6
red      1  0  0  0  1  0  0
apple    1  0  0  0  0  0  0
rainbow  0  1  0  0  0  0  0
purple   0  0  1  0  0  0  0
pickle   0  0  0  1  0  0  0
book     0  0  0  0  1  1  0
yellow   0  0  0  0  0  1  0


In [298]:
def get_similary_table(topic=None):
    if topic==None:
        df = cdf
    else:
        df = cdf.loc[cdf.index.isin(topic)]  #filter by topic
    cnd = df.values
    similarity = cnd.T@cnd #Take dot product to get similarty matrix
    dd = pd.DataFrame(similarity, index=corpus, columns=corpus) #convert to a dataframe
    return dd

In [288]:
def get_similar_review(s, topic):
    df = cdf.loc[cdf.index.isin(topic)] #filter by topic
    cnd = df.values
    similarity = cnd.T@cnd #Take dot product to get similarty matrix
    np.fill_diagonal(similarity,0) #set diagonal elements to 0, to avoid same sentence being returned as output
    dd = pd.DataFrame(similarity, index=corpus, columns=corpus) #convert to a dataframe
    return dd.loc[s].idxmax(axis=0) #filter by sentence and get column name with max value

In [285]:
s = 'i ate a red apple.'
get_similar(s, colors)

'the kid read the book the little red riding hood'

In [286]:
s = 'the kid read the book the little red riding hood'
get_similar(s, things)

'in the book the wizard of oz there was a yellow brick road.'

In [299]:
get_similary_table()

i ate a red apple.  \
i ate a red apple.                                                   2   
There are so many colors in the rainbow.                             0   
the monster was purple and green.                                    0   
the pickle is very green                                             0   
the kid read the book the little red riding hood                     1   
in the book the wizard of oz there was a yellow...                   0   
tom has a green thumb and likes working in a ga...                   0   

                                                    There are so many colors in the rainbow.  \
i ate a red apple.                                                                         0   
There are so many colors in the rainbow.                                                   1   
the monster was purple and green.                                                          0   
the pickle is very green                                                                   0   
the kid read the book the little red riding hood                                           0   
in the book the wizard of oz there was a yellow...                                         0   
tom has a green thumb and likes working in a ga...                                         0   

                                                    the monster was purple and green.  \
i ate a red apple.                                                                  0   
There are so many colors in the rainbow.                                            0   
the monster was purple and green.                                                   1   
the pickle is very green                                                            0   
the kid read the book the little red riding hood                                    0   
in the book the wizard of oz there was a yellow...                                  0   
tom has a green thumb and likes working in a ga...                                  0   

                                                    the pickle is very green  \
i ate a red apple.                                                         0   
There are so many colors in the rainbow.                                   0   
the monster was purple and green.                                          0   
the pickle is very green                                                   1   
the kid read the book the little red riding hood                           0   
in the book the wizard of oz there was a yellow...                         0   
tom has a green thumb and likes working in a ga...                         0   

                                                    the kid read the book the little red riding hood  \
i ate a red apple.                                                                                 1   
There are so many colors in the rainbow.                                                           0   
the monster was purple and green.                                                                  0   
the pickle is very green                                                                           0   
the kid read the book the little red riding hood                                                   2   
in the book the wizard of oz there was a yellow...                                                 1   
tom has a green thumb and likes working in a ga...                                                 0   

                                                    in the book the wizard of oz there was a yellow brick road.  \
i ate a red apple.                                                                                  0             
There are so many colors in the rainbow.                                                            0             
the monster was purple and green.                                                                   0             
the pickle is very green                   

In [331]:
a = pd.DataFrame([[1,2,2],[3,4,5]], columns=['A','B','C'])
print(a)

   A  B  C
0  1  2  2
1  3  4  5


In [337]:
grp = a.groupby([True]*len(a))
grp

In [406]:
data = np.array([['country','time','x','y'],
                ['USA',1, 5, 10],
                ['USA',2, 5, 12],
                ['USA',3,6, 13],
                ['CAN',1,2, 2],
                ['CAN',2,2, 3],
                ['CAN',3,4, 5]],                
               )

df = pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:])

df1 = df.reset_index().set_index(['time','index']).unstack(-1)
print(df1)

        x       y    
index CAN USA CAN USA
time                 
1       2   5   2  10
2       2   5   3  12
3       4   6   5  13


In [387]:
#df1.columns = df1.columns.map('_'.join)

In [388]:
df1

x       y    
index CAN USA CAN USA
time                 
1       2   5   2  10
2       2   5   3  12
3       4   6   5  13

In [389]:
from sklearn.model_selection import TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits = 2, max_train_size=3)

for train_index, test_index in tscv.split(df1):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = df1.iloc[train_index].stack(-1).reset_index()[X_cols].to_numpy(), df1.iloc[test_index].stack(-1).reset_index()[X_cols].to_numpy()
    y_train, y_test = df1.iloc[train_index].stack(-1).reset_index()[y_cols].to_numpy(), df1.iloc[test_index].stack(-1).reset_index()[y_cols].to_numpy()

In [394]:
df1

x       y    
index CAN USA CAN USA
time                 
1       2   5   2  10
2       2   5   3  12
3       4   6   5  13

In [400]:
X_cols = ['time', 'index', 'x']
y_cols = ['y']

In [413]:
print('For - TRAIN: [0 1] TEST: [2]')
print(" ")
print("X_train:")
print(X_train)
print(" ")
print("X_test:")
print(X_test)
print(" ")
print("y_train:")
print(y_train)
print(" ")
print("y_test:")
print(y_test)

For - TRAIN: [0 1] TEST: [2]
 
X_train:
[['1' 'CAN' '2']
 ['1' 'USA' '5']
 ['2' 'CAN' '2']
 ['2' 'USA' '5']]
 
X_test:
[['3' 'CAN' '4']
 ['3' 'USA' '6']]
 
y_train:
[['2']
 ['10']
 ['3']
 ['12']]
 
y_test:
[['5']
 ['13']]


In [441]:
print(sorted(mylist, key=lambda x: x.count('0'), reverse=True))

[['MikeF', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'], ['Bobby', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '1', '0'], ['Felicia', '0', '0', '1', '0', '1', '0', '0', '0', '0', '1', '0', '1', '0', '0'], ['Shannon', '0', '1', '0', '0', '1', '0', '0', '0', '0', '1', '0', '1', '0', '0'], ['Jake', '0', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0'], ['MikeP', '0', '0', '1', '0', '1', '0', '0', '0', '1', '1', '0', '1', '0', '0'], ['Adam', '0', '1', '0', '1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0'], ['Tom', '0', '1', '1', '1', '1', '0', '0', '0', '1', '1', '1', '1', '0', '0']]


In [442]:
import pandas as pd

df = pd.DataFrame({'ID': [111, 222, 222, 333, 333, 444, 444, 444, 555, 555, 555, 555], 
                   'Name': ['David','Carl','Carl','Jane','Jane','Mike','Mike','Mike','Jake','Jake','Jake','Jake'],
                  'LE': ['AAA','AAA','BBB','BBB','CCC','AAA','BBB','CCC','AAA','BBB','CCC','DDD']})

print(df)

     ID   Name   LE
0   111  David  AAA
1   222   Carl  AAA
2   222   Carl  BBB
3   333   Jane  BBB
4   333   Jane  CCC
5   444   Mike  AAA
6   444   Mike  BBB
7   444   Mike  CCC
8   555   Jake  AAA
9   555   Jake  BBB
10  555   Jake  CCC
11  555   Jake  DDD


In [469]:
print(df[~(df.duplicated(['LE']) & (df['LE']=='AAA'))].reset_index(drop=True))

    ID   Name   LE
0  111  David  AAA
1  222   Carl  BBB
2  333   Jane  BBB
3  333   Jane  CCC
4  444   Mike  BBB
5  444   Mike  CCC
6  555   Jake  BBB
7  555   Jake  CCC
8  555   Jake  DDD


In [ ]:
ID  |State  |Invoice|Price|Email 
1000|Texas  |1      |2    |texas@test.com
1000|Texas  |2      |5    |texas@test.com
1001|Alabama|3      |4    |alabama@test.com
1000|Texas  |4      |8    |texas@test.com
1002|Georgia|5      |3    |georgia@test.com
1001|Alabama|6      |6    |alabama@test.com

In [471]:
df = pd.DataFrame({'ID':[1000,1000,1001,1000,1002,1001],
 'State':['Texas','Texas','Alabama','Texas','Georgia','Alabama'],
'Invoice':[1,2,3,4,5,6],
'Price':[2,5,4,8,3,6],
'Email':['texas@test.com','texas@test.com','alabama@test.com','texas@test.com','georgia@test.com','alabama@test.com']})

In [479]:
df1, df2, df3 = [i[1] for i in df.groupby(['ID'])]

In [485]:
print(df3)

     ID    State  Invoice  Price             Email
4  1002  Georgia        5      3  georgia@test.com


In [493]:
df1, df2, df3 = [df[df['ID']==i] for i in df['ID'].unique()]

In [496]:
df3

ID    State  Invoice  Price             Email
4  1002  Georgia        5      3  georgia@test.com

In [507]:
df

ID    State  Invoice  Price             Email
0  1000    Texas        1      2    texas@test.com
1  1000    Texas        2      5    texas@test.com
2  1001  Alabama        3      4  alabama@test.com
3  1000    Texas        4      8    texas@test.com
4  1002  Georgia        5      3  georgia@test.com
5  1001  Alabama        6      6  alabama@test.com

In [509]:
a = np.array([0, 1, 2, 10, 11, 20, 21, 22, 23])
chunks = np.array([3, 2, 4])
repeats = np.array([1, 3, 2])

In [518]:
a

array([ 0,  1,  2, 10, 11, 20, 21, 22, 23])

In [531]:
a

array([ 0,  1,  2, 10, 11, 20, 21, 22, 23])

In [577]:
a = np.random.randint(0,50, size=(100000,))
chunks = np.random.randint(0,10, size=(4000,))
repeats = np.random.randint(0,10, size=(4000,))

In [578]:
def create_ranges(starts, ends, l):
        clens = l.cumsum()
        ids = np.ones(clens[-1],dtype=int)
        ids[0] = starts[0]
        ids[clens[:-1]] = starts[1:] - ends[:-1]+1
        out = ids.cumsum()
        return out

def f():
    s = np.r_[0,chunks.cumsum()]
    starts = a[np.repeat(s[:-1],repeats)]
    l = np.repeat(chunks, repeats)
    ends = starts+l
    out = create_ranges(starts, ends, l)

In [579]:
#Divakar
%timeit f()

595 µs ± 59.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [580]:
#Akshay
%timeit np.concatenate(np.repeat(np.split(a, np.cumsum(chunks))[:-1], repeats))

8.03 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [581]:
#Vladi
%timeit result = np.concatenate([ np.tile(tbl, rpt) for tbl, rpt in zip(np.split(a, np.cumsum(chunks[:-1])), repeats) ])

25.9 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [603]:
import itertools

w = np.random.randint(1,400,size=1000) #np.array([1, 2, 3, 4])
x = np.random.randint(1,400,size=1000) #np.array([1, 2, 3, 4])

In [605]:
#[i for i in itertools.product(w,x) if i[0]<i[1]]

In [606]:
%timeit [i for i in itertools.product(w,x) if i[0]<i[1]]

128 ms ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [607]:
def f():
    r,c = np.nonzero(w[:,None]<x) # or np.less.outer(w,x)
    np.c_[w[r], x[c]]
    
%timeit f()

12.4 ms ± 18 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [612]:
a = np.array([0,0,1,1,2,0])

In [617]:
np.transpose(np.nonzero(a))

array([[2],
       [3],
       [4]])

In [637]:
import scipy
import pickle

I = np.eye(10000)  #Had 10000 nonzero values along diagonal
S = scipy.sparse.csr_matrix(I)
S

<10000x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [629]:
#Pickle dump
file = open("S.pickle",'wb') #160kb
pickle.dump(S, file)

#Pickle load
file = open("S.pickle",'rb') 
S = pickle.load(file)

In [630]:
def a():
    l
    h

In [631]:
S

<10000x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [634]:
S.toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [641]:
pos = np.array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [0, 1, 6, 7],
       [2, 3, 6, 7],
       [2, 3, 8, 9],
       [4, 5, 8, 9],
       [6, 7, 8, 9]])

pos = pos.reshape((7,1,4))
pos

array([[[0, 1, 2, 3]],

       [[2, 3, 4, 5]],

       [[0, 1, 6, 7]],

       [[2, 3, 6, 7]],

       [[2, 3, 8, 9]],

       [[4, 5, 8, 9]],

       [[6, 7, 8, 9]]])

In [642]:
af = np.zeros((7,2*nnos,4))

NameError: name 'nnos' is not defined

In [640]:
for i in range(7):
    print(i,pos[i],pos[0])

0 [[0 1 2 3]] [[0 1 2 3]]
1 [[2 3 4 5]] [[0 1 2 3]]
2 [[0 1 6 7]] [[0 1 2 3]]
3 [[2 3 6 7]] [[0 1 2 3]]
4 [[2 3 8 9]] [[0 1 2 3]]
5 [[4 5 8 9]] [[0 1 2 3]]
6 [[6 7 8 9]] [[0 1 2 3]]


In [774]:
df = pd.DataFrame({'A':[0,0,1], 
                   'B':[1,0,0], 
                   'C':[0,0,0], 
                   'D':[1,0,1], 
                   'E':[1,0,1]})

In [761]:
df['new_column'] = df.apply(lambda x: ', '.join(list(x[x!=0].index)), axis=1)

print(df)

   A  B  C  D  E new_column
0  0  1  0  1  1    B, D, E
1  0  0  0  0  0           
2  1  0  0  1  1    A, D, E


In [764]:
df.dot(df.columns)

0    BDE
1       
2    ADE
dtype: object

In [765]:
df

A  B  C  D  E
0  0  1  0  1  1
1  0  0  0  0  0
2  1  0  0  1  1

In [766]:
df.columns

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [775]:
df['new_column'] = (df @ df.columns).str.join(', ')

In [776]:
print(df)

   A  B  C  D  E new_column
0  0  1  0  1  1    B, D, E
1  0  0  0  0  0           
2  1  0  0  1  1    A, D, E
