# Solving a system of linear equations

In [56]:
from scipy import linalg
import numpy as np

In [57]:
m = np.array([[2,3,5],[4,-2,-7], [9,5,-3]])

In [58]:
y = np.array([1, 8, 2])

In [59]:
lu, piv = linalg.lu_factor(m)

In [60]:
lu

array([[ 9.        ,  5.        , -3.        ],
       [ 0.44444444, -4.22222222, -5.66666667],
       [ 0.22222222, -0.44736842,  3.13157895]])

In [61]:
linalg.lu_solve((lu, piv), y)

array([ 2.44537815, -3.28571429,  1.19327731])

# Matrix inverse

In [62]:
n = np.array([[1,0,2,0], [1,1,0,0], [1,2,0,1], [1,1,1,1]])

In [78]:
linalg.inv(n)

array([[-1.,  2., -2.,  2.],
       [ 1., -1.,  2., -2.],
       [ 1., -1.,  1., -1.],
       [-1.,  0., -1.,  2.]])

# Another way of solving linear eq (A is sq and invertable)

- $ Ax = b $
- $ x = A^{-1}b $

In [68]:
np.dot(linalg.inv(m), y)

array([ 2.44537815, -3.28571429,  1.19327731])

# Another way using moore-penrose pseudo inverse

(not recommended due to precision issues)

This method works for non square and non invertable matrices, under assumption that the matrix has linearly independent columns.

- $ Ax = b $
- $ A^TAx = A^Tb $
- $ x = (A^TA)^{-1}A^Tb $

In [120]:
np.dot(np.dot(linalg.inv(np.dot(m.T, m)), m.T), y)

array([ 2.44537815, -3.28571429,  1.19327731])

In [121]:
k = np.array([[1,3,0,0],[0,0,1,0], [0,0,0,1]])
w = np.array([3,9,-4])

In [122]:
def pseudo_inv(A):
    return np.dot(linalg.inv(np.dot(A.T, A)), A.T)

In [123]:
x = np.dot(pseudo_inv(k), w)
x

array([ 0.,  0.,  9., -4.])

In [124]:
np.dot(k,x)

array([ 0.,  9., -4.])

Methods used usually involve iteration methods such as - Richardson method, Jacobi method, Gaub-Seidel method, successive over relaxation method, krylov subspace methods (conjugate gradients, generalized minimal residual, biconjugate gradients)

# Inner and outer product of matrices

In [125]:
a = np.array([1,2,3,4,5,6])
b = np.array([10,20,30,40,50,60])

In [129]:
#Dot product = a^T.b
# (1Xn).(nX1) = (nXn)

np.dot(a,b)

910

In [131]:
#outer product = a.b^T
# (nX1).(1Xn) = (nXn)

np.outer(a,b)

array([[ 10,  20,  30,  40,  50,  60],
       [ 20,  40,  60,  80, 100, 120],
       [ 30,  60,  90, 120, 150, 180],
       [ 40,  80, 120, 160, 200, 240],
       [ 50, 100, 150, 200, 250, 300],
       [ 60, 120, 180, 240, 300, 360]])

In [138]:
np.dot(a.reshape(-1,1), b.reshape(1,-1))

array([[ 10,  20,  30,  40,  50,  60],
       [ 20,  40,  60,  80, 100, 120],
       [ 30,  60,  90, 120, 150, 180],
       [ 40,  80, 120, 160, 200, 240],
       [ 50, 100, 150, 200, 250, 300],
       [ 60, 120, 180, 240, 300, 360]])