## GRE Verbal

**Corroborated** - confirm / give support to
- The professor corroborated to Tim's answer
- Most of the representatives corroborated with the amendments

**Gainsay (Gainsaid)** - Deny / Contradict  ('Against' + 'say')
- No one was able to gainsay his claims
- Trump gainsaid all the accusitions made against him

**Derided** - express contempt for, ridicule   (latin: scoff at)
- The decision was derided by the environmentalists
- His brother asked him not to deride his decision

**Denigrated** - criticize unfairly, disparage ('de' - away completely, 'niger' - black = make dark, criticize (?))
- Doom and gloom merchants who denigrate their country
- Hillary denigrated Trump's methods on the forum

**Astute** - having or showing an ability to accurately assess situations and turn this to one's advantage
- Tim was quite an astute businessman

**Recondite** - Little known, abtruse, obscure  ('Re' - back, 'Condere' - put together)
- The book is full of decondite information
- The GOT character Recon is quite recondite

**Clemency** - Mercy, lenience
- The defendant made an appeal for clemency

**Adulation** - Excessive admiration or praise
- He found it difficult to cope up with the adulation of the fans

**Refractory** - Stubborn or unmanageable (tech - substance that is resistant to heat) (latin: stubborn)
- The phone manufacturer was extremely refractory during the discussion
- His refractory horse had to be brought under control

**Injuction** - An authoritative warning or order (latin: impose, enjoin)
- This allusion to the scriptural injuction to love one's neighbour

**Allusion** - An indirect or passing reference  (allude - 'ad': towards, 'ludere': to play = hint at, suggest)
- He made an allusion to the rick and morty series

**Circumlocute** - An indirect way of expressing something (circum - around, locute - talk)
- The story rushes from there, with dizzying circumlocutions

**Disconcerting** - Causing one to feel unsettled ('des' - reversal + 'concerter' - bring together)
- He had a disconcerting habit of offering jobs to people he met at dinner parties

**Mendacious** - Not telling truth, lying ('mendum' - fault)
- Mendacious propoganda

**Ingenuous** - Innocent and unsuspecting  ('ingenuus' : native/inborn)
- He eyed her with wide ingenuous eyes

In [78]:
sentences = ['the big brown fox', 'hellow world', 'hi there friend']

In [79]:
from sklearn.feature_extraction.text import CountVectorizer

In [80]:
cnt = CountVectorizer(stop_words=None)
cnt.fit(sentences)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [105]:
vocab = cnt.vocabulary_
vocab

{'the': 6,
 'big': 0,
 'brown': 1,
 'fox': 2,
 'hellow': 4,
 'world': 8,
 'hi': 5,
 'there': 7,
 'friend': 3}

In [130]:
return_cnt('hi')

array([0, 0, 0, 0, 0, 1, 0, 0, 0])

In [85]:
cnt.transform([sentences[1]]).todense()

matrix([[0, 0, 0, 0, 1, 0, 0, 0, 1]])

In [90]:
emb = 5

In [91]:
word_embeddings = np.random.random((len(vocab), emb))

In [92]:
word_embeddings

array([[0.53115761, 0.85076478, 0.31230391, 0.55803953, 0.62488131],
       [0.23701296, 0.00734163, 0.99430138, 0.26813267, 0.25866758],
       [0.51680929, 0.96583274, 0.25897914, 0.33958891, 0.72627358],
       [0.53199947, 0.3869284 , 0.95228049, 0.09519013, 0.69128872],
       [0.32144083, 0.14510167, 0.37982137, 0.46119968, 0.93653618],
       [0.43961615, 0.332439  , 0.33833768, 0.44745944, 0.78975891],
       [0.109915  , 0.01313985, 0.51010552, 0.63095788, 0.1759848 ],
       [0.88242   , 0.97171065, 0.55148901, 0.12316374, 0.6860986 ],
       [0.89968045, 0.49305493, 0.78048509, 0.63107914, 0.81998625]])

In [6]:
sent = 3

In [123]:
xxx = [np.array([return_cnt(word) for word in sentence.split(' ')]) for sentence in sentences]

In [122]:
def return_cnt(word):
    return np.array(cnt.transform([word]).todense()).ravel()

1. Download GLOVE
2. Get GLOVE vocabulary
3. Define a CNT with GLOVE vocab
4. Fit CNT on sentences
5. Pass each sentence, word by word using FIT s

In [129]:
word_embeddings

array([[0.53115761, 0.85076478, 0.31230391, 0.55803953, 0.62488131],
       [0.23701296, 0.00734163, 0.99430138, 0.26813267, 0.25866758],
       [0.51680929, 0.96583274, 0.25897914, 0.33958891, 0.72627358],
       [0.53199947, 0.3869284 , 0.95228049, 0.09519013, 0.69128872],
       [0.32144083, 0.14510167, 0.37982137, 0.46119968, 0.93653618],
       [0.43961615, 0.332439  , 0.33833768, 0.44745944, 0.78975891],
       [0.109915  , 0.01313985, 0.51010552, 0.63095788, 0.1759848 ],
       [0.88242   , 0.97171065, 0.55148901, 0.12316374, 0.6860986 ],
       [0.89968045, 0.49305493, 0.78048509, 0.63107914, 0.81998625]])

In [ ]:
[return_cnt(word) for word in sentence.split(' ')]

In [128]:
[np.dot(i,word_embeddings) for i in xxx]

[array([[0.109915  , 0.01313985, 0.51010552, 0.63095788, 0.1759848 ],
        [0.53115761, 0.85076478, 0.31230391, 0.55803953, 0.62488131],
        [0.23701296, 0.00734163, 0.99430138, 0.26813267, 0.25866758],
        [0.51680929, 0.96583274, 0.25897914, 0.33958891, 0.72627358]]),
 array([[0.32144083, 0.14510167, 0.37982137, 0.46119968, 0.93653618],
        [0.89968045, 0.49305493, 0.78048509, 0.63107914, 0.81998625]]),
 array([[0.43961615, 0.332439  , 0.33833768, 0.44745944, 0.78975891],
        [0.88242   , 0.97171065, 0.55148901, 0.12316374, 0.6860986 ],
        [0.53199947, 0.3869284 , 0.95228049, 0.09519013, 0.69128872]])]

In [93]:
[cnt.transform([i]).todense() for i in sentences]

[matrix([[1, 1, 1, 0, 0, 0, 1, 0, 0]]),
 matrix([[0, 0, 0, 0, 1, 0, 0, 0, 1]]),
 matrix([[0, 0, 0, 1, 0, 1, 0, 1, 0]])]

In [1]:
import numpy as np

In [76]:
onehot = np.random.randint(0,2,(sent, vocab))

In [77]:
onehot

array([[1, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])